// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbActividadesPorOptante
    {
        public int AcpeId { get; set; }
        public int ActiId { get; set; }
        public int OptaId { get; set; }
        public int? AcpeHorasCumplidas { get; set; }
        public string AcpeObservacion { get; set; }
        public int? AcpeUsuarioCreacion { get; set; }
        public DateTime? AcpeFechaCreacion { get; set; }
        public int? AcpeUsuarioModificacion { get; set; }
        public DateTime? AcpeFechaModificacion { get; set; }
        public bool? AcpeEstado { get; set; }

        public virtual TbUsuarios AcpeUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios AcpeUsuarioModificacionNavigation { get; set; }
        public virtual TbActividades Acti { get; set; }
        public virtual TbOptantes Opta { get; set; }
    }
}