// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbActividades", Schema = "Gest")]
    public partial class tbActividades
    {
        public tbActividades()
        {
            tbActividadesPorOptante = new HashSet<tbActividadesPorOptante>();
            tbEmpleadosPorActividad = new HashSet<tbEmpleadosPorActividad>();
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
        }

        [Key]
        public int acti_Id { get; set; }
        public int? comp_Id { get; set; }
        [StringLength(4)]
        public string muni_Id { get; set; }
        public bool acti_PresencialOVirtual { get; set; }
        [Required]
        [StringLength(100)]
        public string acti_NombreActividad { get; set; }
        [Required]
        [StringLength(100)]
        public string acti_DescripcionActividad { get; set; }
        public TimeSpan? acti_Horas { get; set; }
        [Column(TypeName = "date")]
        public DateTime acti_FechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? acti_FechaFinal { get; set; }
        [StringLength(100)]
        public string acti_DireccionExacta { get; set; }
        public int? acti_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? acti_FechaCreacion { get; set; }
        public int? acti_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? acti_FechaModificacion { get; set; }
        public bool? acti_Estado { get; set; }

        [ForeignKey(nameof(acti_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbActividadesacti_UsuarioCreacionNavigation))]
        public virtual tbUsuarios acti_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(acti_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbActividadesacti_UsuarioModificacionNavigation))]
        public virtual tbUsuarios acti_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(comp_Id))]
        [InverseProperty(nameof(tbComponentes.tbActividades))]
        public virtual tbComponentes comp { get; set; }
        [ForeignKey(nameof(muni_Id))]
        [InverseProperty(nameof(tbMunicipios.tbActividades))]
        public virtual tbMunicipios muni { get; set; }
        [InverseProperty("acti")]
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptante { get; set; }
        [InverseProperty("acti")]
        public virtual ICollection<tbEmpleadosPorActividad> tbEmpleadosPorActividad { get; set; }
        [InverseProperty("acti")]
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
    }
}