// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbActividades
    {
        public tbActividades()
        {
            tbActividadesPorOptante = new HashSet<tbActividadesPorOptante>();
            tbEmpleadosPorActividad = new HashSet<tbEmpleadosPorActividad>();
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
        }

        public int acti_Id { get; set; }
        public int? comp_Id { get; set; }
        public string muni_Id { get; set; }
        public bool acti_PresencialOVirtual { get; set; }
        public string acti_NombreActividad { get; set; }
        public string acti_DescripcionActividad { get; set; }
        public TimeSpan? acti_Horas { get; set; }
        public DateTime acti_FechaInicio { get; set; }
        public DateTime? acti_FechaFinal { get; set; }
        public string acti_DireccionExacta { get; set; }
        public int? acti_UsuarioCreacion { get; set; }
        public DateTime? acti_FechaCreacion { get; set; }
        public int? acti_UsuarioModificacion { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }
        public bool? acti_Estado { get; set; }

        public virtual tbUsuarios acti_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios acti_UsuarioModificacionNavigation { get; set; }
        public virtual tbComponentes comp { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptante { get; set; }
        public virtual ICollection<tbEmpleadosPorActividad> tbEmpleadosPorActividad { get; set; }
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
    }
}