// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbActividades
    {
        public TbActividades()
        {
            TbActividadesPorOptante = new HashSet<TbActividadesPorOptante>();
            TbEmpleadosPorActividad = new HashSet<TbEmpleadosPorActividad>();
            TbForosPorActividad = new HashSet<TbForosPorActividad>();
        }

        public int ActiId { get; set; }
        public int? CompId { get; set; }
        public string MuniId { get; set; }
        public bool ActiPresencialOvirtual { get; set; }
        public string ActiNombreActividad { get; set; }
        public string ActiDescripcionActividad { get; set; }
        public TimeSpan? ActiHoras { get; set; }
        public DateTime ActiFechaInicio { get; set; }
        public DateTime? ActiFechaFinal { get; set; }
        public string ActiDireccionExacta { get; set; }
        public int? ActiUsuarioCreacion { get; set; }
        public DateTime? ActiFechaCreacion { get; set; }
        public int? ActiUsuarioModificacion { get; set; }
        public DateTime? ActiFechaModificacion { get; set; }
        public bool? ActiEstado { get; set; }

        public virtual TbUsuarios ActiUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios ActiUsuarioModificacionNavigation { get; set; }
        public virtual TbComponentes Comp { get; set; }
        public virtual TbMunicipios Muni { get; set; }
        public virtual ICollection<TbActividadesPorOptante> TbActividadesPorOptante { get; set; }
        public virtual ICollection<TbEmpleadosPorActividad> TbEmpleadosPorActividad { get; set; }
        public virtual ICollection<TbForosPorActividad> TbForosPorActividad { get; set; }
    }
}