// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbActividadesPorOptante
    {
        public int acpe_Id { get; set; }
        public int acti_Id { get; set; }
        public int opta_Id { get; set; }
        public int? acpe_HorasCumplidas { get; set; }
        public string acpe_Observacion { get; set; }
        public int? acpe_UsuarioCreacion { get; set; }
        public DateTime? acpe_FechaCreacion { get; set; }
        public int? acpe_UsuarioModificacion { get; set; }
        public DateTime? acpe_FechaModificacion { get; set; }
        public bool? acpe_Estado { get; set; }

        public virtual tbUsuarios acpe_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios acpe_UsuarioModificacionNavigation { get; set; }
        public virtual tbActividades acti { get; set; }
        public virtual tbOptantes opta { get; set; }
    }
}