// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbBancos
    {
        public TbBancos()
        {
            TbOptantes = new HashSet<TbOptantes>();
        }

        public int BancId { get; set; }
        public string BancDescripcion { get; set; }
        public int? BancUsuarioCreacion { get; set; }
        public DateTime? BancFechaCreacion { get; set; }
        public int? BancUsuarioModificacion { get; set; }
        public DateTime? BancFechaModificacion { get; set; }
        public bool? BancEstado { get; set; }

        public virtual TbUsuarios BancUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios BancUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
    }
}