// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbBancos", Schema = "Gral")]
    [Index(nameof(banc_Descripcion), Name = "UQ_banc_Descripcion", IsUnique = true)]
    public partial class tbBancos
    {
        public tbBancos()
        {
            tbOptantes = new HashSet<tbOptantes>();
        }

        [Key]
        public int banc_Id { get; set; }
        [Required]
        [StringLength(60)]
        public string banc_Descripcion { get; set; }
        public int? banc_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? banc_FechaCreacion { get; set; }
        public int? banc_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? banc_FechaModificacion { get; set; }
        public bool? banc_Estado { get; set; }

        [ForeignKey(nameof(banc_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbBancosbanc_UsuarioCreacionNavigation))]
        public virtual tbUsuarios banc_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(banc_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbBancosbanc_UsuarioModificacionNavigation))]
        public virtual tbUsuarios banc_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("banc")]
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}