// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbBeneficios
    {
        public TbBeneficios()
        {
            TbBeneficiosPorOptante = new HashSet<TbBeneficiosPorOptante>();
        }

        public int BeneId { get; set; }
        public string BeneNombreBeneficio { get; set; }
        public string BeneDescripcionBeneficio { get; set; }
        public decimal BeneCantidad { get; set; }
        public int? BeneUsuarioCreacion { get; set; }
        public DateTime? BeneFechaCreacion { get; set; }
        public int? BeneUsuarioModificacion { get; set; }
        public DateTime? BeneFechaModificacion { get; set; }
        public bool? BeneEstado { get; set; }

        public virtual TbUsuarios BeneUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios BeneUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbBeneficiosPorOptante> TbBeneficiosPorOptante { get; set; }
    }
}