// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbBeneficiosPorOptante
    {
        public int BepeId { get; set; }
        public int BeneId { get; set; }
        public int OptaId { get; set; }

        public virtual TbBeneficios Bene { get; set; }
        public virtual TbOptantes Opta { get; set; }
    }
}