// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbBeneficios
    {
        public tbBeneficios()
        {
            tbBeneficiosPorOptante = new HashSet<tbBeneficiosPorOptante>();
        }

        public int bene_Id { get; set; }
        public string bene_NombreBeneficio { get; set; }
        public string bene_DescripcionBeneficio { get; set; }
        public decimal bene_Cantidad { get; set; }
        public int? bene_UsuarioCreacion { get; set; }
        public DateTime? bene_FechaCreacion { get; set; }
        public int? bene_UsuarioModificacion { get; set; }
        public DateTime? bene_FechaModificacion { get; set; }
        public bool? bene_Estado { get; set; }

        public virtual tbUsuarios bene_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios bene_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbBeneficiosPorOptante> tbBeneficiosPorOptante { get; set; }
    }
}