// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbBeneficiosPorOptante", Schema = "Gest")]
    public partial class tbBeneficiosPorOptante
    {
        [Key]
        public int bepe_Id { get; set; }
        public int bene_Id { get; set; }
        public int opta_Id { get; set; }

        [ForeignKey(nameof(bene_Id))]
        [InverseProperty(nameof(tbBeneficios.tbBeneficiosPorOptante))]
        public virtual tbBeneficios bene { get; set; }
        [ForeignKey(nameof(opta_Id))]
        [InverseProperty(nameof(tbOptantes.tbBeneficiosPorOptante))]
        public virtual tbOptantes opta { get; set; }
    }
}