// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbCarreras", Schema = "Gral")]
    [Index(nameof(carr_DescripcionCarrera), Name = "UQ__tbCarrer__C7EE739B9767C6B9", IsUnique = true)]
    public partial class tbCarreras
    {
        public tbCarreras()
        {
            tbCarreraPorFacultadPorRegional = new HashSet<tbCarreraPorFacultadPorRegional>();
        }

        [Key]
        public int carr_Id { get; set; }
        [Required]
        [StringLength(60)]
        public string carr_DescripcionCarrera { get; set; }
        public int? carr_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? carr_FechaCreacion { get; set; }
        public int? carr_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? carr_FechaModificacion { get; set; }
        public bool? carr_Estado { get; set; }

        [ForeignKey(nameof(carr_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbCarrerascarr_UsuarioCreacionNavigation))]
        public virtual tbUsuarios carr_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(carr_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbCarrerascarr_UsuarioModificacionNavigation))]
        public virtual tbUsuarios carr_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("carr")]
        public virtual ICollection<tbCarreraPorFacultadPorRegional> tbCarreraPorFacultadPorRegional { get; set; }
    }
}