// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbCarreraPorFacultadPorRegional
    {
        public TbCarreraPorFacultadPorRegional()
        {
            TbOptantes = new HashSet<TbOptantes>();
        }

        public int CafrId { get; set; }
        public int FareId { get; set; }
        public int CarrId { get; set; }

        public virtual TbCarreras Carr { get; set; }
        public virtual TbFacultadPorRegional Fare { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
    }
}