// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbCarreraPorFacultadPorRegional", Schema = "Gral")]
    public partial class tbCarreraPorFacultadPorRegional
    {
        public tbCarreraPorFacultadPorRegional()
        {
            tbOptantes = new HashSet<tbOptantes>();
        }

        [Key]
        public int cafr_Id { get; set; }
        public int fare_Id { get; set; }
        public int carr_Id { get; set; }
        [StringLength(100)]
        public string cafr_DescripcionCarreraEspecifico { get; set; }

        [ForeignKey(nameof(carr_Id))]
        [InverseProperty(nameof(tbCarreras.tbCarreraPorFacultadPorRegional))]
        public virtual tbCarreras carr { get; set; }
        [ForeignKey(nameof(fare_Id))]
        [InverseProperty(nameof(tbFacultadPorRegional.tbCarreraPorFacultadPorRegional))]
        public virtual tbFacultadPorRegional fare { get; set; }
        [InverseProperty("cafr")]
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}