// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbCarreras
    {
        public tbCarreras()
        {
            tbCarreraPorFacultadPorRegional = new HashSet<tbCarreraPorFacultadPorRegional>();
        }

        public int carr_Id { get; set; }
        public string carr_DescripcionCarrera { get; set; }
        public int? carr_UsuarioCreacion { get; set; }
        public DateTime? carr_FechaCreacion { get; set; }
        public int? carr_UsuarioModificacion { get; set; }
        public DateTime? carr_FechaModificacion { get; set; }
        public bool? carr_Estado { get; set; }

        public virtual tbUsuarios carr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios carr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCarreraPorFacultadPorRegional> tbCarreraPorFacultadPorRegional { get; set; }
    }
}