// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbCarreras
    {
        public TbCarreras()
        {
            TbCarreraPorFacultadPorRegional = new HashSet<TbCarreraPorFacultadPorRegional>();
        }

        public int CarrId { get; set; }
        public string CarrDescripcionCarrera { get; set; }
        public int? CarrUsuarioCreacion { get; set; }
        public DateTime? CarrFechaCreacion { get; set; }
        public int? CarrUsuarioModificacion { get; set; }
        public DateTime? CarrFechaModificacion { get; set; }
        public bool? CarrEstado { get; set; }

        public virtual TbUsuarios CarrUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios CarrUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbCarreraPorFacultadPorRegional> TbCarreraPorFacultadPorRegional { get; set; }
    }
}