// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbComponentes
    {
        public tbComponentes()
        {
            tbActividades = new HashSet<tbActividades>();
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
            tbHojaTiempo = new HashSet<tbHojaTiempo>();
            tbOptantes = new HashSet<tbOptantes>();
        }

        public int comp_Id { get; set; }
        public int pryt_Id { get; set; }
        public string comp_NombreComponente { get; set; }
        public string comp_DescripcionComponente { get; set; }
        public TimeSpan comp_HorasAsignadas { get; set; }
        public TimeSpan? comp_HorasCumplidas { get; set; }
        public DateTime comp_FechaInicio { get; set; }
        public DateTime comp_FechaFin { get; set; }
        public string comp_Observacion { get; set; }
        public bool? comp_ComponenteFinalizado { get; set; }
        public int? comp_UsuarioCreacion { get; set; }
        public DateTime? comp_FechaCreacion { get; set; }
        public int? comp_UsuarioModificacion { get; set; }
        public DateTime? comp_FechaModificacion { get; set; }
        public bool? comp_Estado { get; set; }

        public virtual tbUsuarios comp_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios comp_UsuarioModificacionNavigation { get; set; }
        public virtual tbProyectos pryt { get; set; }
        public virtual ICollection<tbActividades> tbActividades { get; set; }
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
        public virtual ICollection<tbHojaTiempo> tbHojaTiempo { get; set; }
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}