// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbComponentesPorRegionalPorEmpleado", Schema = "Gest")]
    public partial class tbComponentesPorRegionalPorEmpleado
    {
        [Key]
        public int core_Id { get; set; }
        public int comp_Id { get; set; }
        public int reco_Id { get; set; }
        public int empl_Id { get; set; }

        [ForeignKey(nameof(comp_Id))]
        [InverseProperty(nameof(tbComponentes.tbComponentesPorRegionalPorEmpleado))]
        public virtual tbComponentes comp { get; set; }
        [ForeignKey(nameof(empl_Id))]
        [InverseProperty(nameof(tbEmpleados.tbComponentesPorRegionalPorEmpleado))]
        public virtual tbEmpleados empl { get; set; }
        [ForeignKey(nameof(reco_Id))]
        [InverseProperty(nameof(tbRegionalCorporativa.tbComponentesPorRegionalPorEmpleado))]
        public virtual tbRegionalCorporativa reco { get; set; }
    }
}