// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbComponentes", Schema = "Gest")]
    [Index(nameof(comp_NombreComponente), Name = "UQ__tbCompon__918F2BC481C11832", IsUnique = true)]
    public partial class tbComponentes
    {
        public tbComponentes()
        {
            tbActividades = new HashSet<tbActividades>();
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
            tbHojaTiempo = new HashSet<tbHojaTiempo>();
            tbOptantes = new HashSet<tbOptantes>();
        }

        [Key]
        public int comp_Id { get; set; }
        public int pryt_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string comp_NombreComponente { get; set; }
        [Required]
        public string comp_DescripcionComponente { get; set; }
        public TimeSpan comp_HorasAsignadas { get; set; }
        public TimeSpan? comp_HorasCumplidas { get; set; }
        [Column(TypeName = "date")]
        public DateTime comp_FechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime comp_FechaFin { get; set; }
        public string comp_Observacion { get; set; }
        public bool? comp_ComponenteFinalizado { get; set; }
        public int? comp_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? comp_FechaCreacion { get; set; }
        public int? comp_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? comp_FechaModificacion { get; set; }
        public bool? comp_Estado { get; set; }

        [ForeignKey(nameof(comp_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbComponentescomp_UsuarioCreacionNavigation))]
        public virtual tbUsuarios comp_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(comp_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbComponentescomp_UsuarioModificacionNavigation))]
        public virtual tbUsuarios comp_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(pryt_Id))]
        [InverseProperty(nameof(tbProyectos.tbComponentes))]
        public virtual tbProyectos pryt { get; set; }
        [InverseProperty("comp")]
        public virtual ICollection<tbActividades> tbActividades { get; set; }
        [InverseProperty("comp")]
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
        [InverseProperty("comp")]
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
        [InverseProperty("comp")]
        public virtual ICollection<tbHojaTiempo> tbHojaTiempo { get; set; }
        [InverseProperty("comp")]
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}