// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbComponentesPorRegionalPorEmpleado
    {
        public int CoreId { get; set; }
        public int CompId { get; set; }
        public int RecoId { get; set; }
        public int EmplId { get; set; }

        public virtual TbComponentes Comp { get; set; }
        public virtual TbEmpleados Empl { get; set; }
        public virtual TbRegionalCorporativa Reco { get; set; }
    }
}