// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbComponentesPorRegionalPorEmpleado
    {
        public int core_Id { get; set; }
        public int comp_Id { get; set; }
        public int reco_Id { get; set; }
        public int empl_Id { get; set; }

        public virtual tbComponentes comp { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbRegionalCorporativa reco { get; set; }
    }
}