// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbComponentes
    {
        public TbComponentes()
        {
            TbActividades = new HashSet<TbActividades>();
            TbComponentesPorRegionalPorEmpleado = new HashSet<TbComponentesPorRegionalPorEmpleado>();
            TbForosPorActividad = new HashSet<TbForosPorActividad>();
            TbHojaTiempo = new HashSet<TbHojaTiempo>();
            TbOptantes = new HashSet<TbOptantes>();
        }

        public int CompId { get; set; }
        public int PrytId { get; set; }
        public string CompNombreComponente { get; set; }
        public string CompDescripcionComponente { get; set; }
        public TimeSpan CompHorasAsignadas { get; set; }
        public TimeSpan? CompHorasCumplidas { get; set; }
        public DateTime CompFechaInicio { get; set; }
        public DateTime CompFechaFin { get; set; }
        public string CompObservacion { get; set; }
        public bool? CompComponenteFinalizado { get; set; }
        public int? CompUsuarioCreacion { get; set; }
        public DateTime? CompFechaCreacion { get; set; }
        public int? CompUsuarioModificacion { get; set; }
        public DateTime? CompFechaModificacion { get; set; }
        public bool? CompEstado { get; set; }

        public virtual TbUsuarios CompUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios CompUsuarioModificacionNavigation { get; set; }
        public virtual TbProyectos Pryt { get; set; }
        public virtual ICollection<TbActividades> TbActividades { get; set; }
        public virtual ICollection<TbComponentesPorRegionalPorEmpleado> TbComponentesPorRegionalPorEmpleado { get; set; }
        public virtual ICollection<TbForosPorActividad> TbForosPorActividad { get; set; }
        public virtual ICollection<TbHojaTiempo> TbHojaTiempo { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
    }
}