// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbCuestionarios", Schema = "Gest")]
    public partial class tbCuestionarios
    {
        public tbCuestionarios()
        {
            tbPreguntasPorCuestionario = new HashSet<tbPreguntasPorCuestionario>();
        }

        [Key]
        public int cues_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string cues_NombreCuestionario { get; set; }
        [Required]
        public string cues_DescripcionCuestionario { get; set; }
        public bool cues_EsCalificado { get; set; }
        [Column(TypeName = "decimal(2, 1)")]
        public decimal? cues_Puntuacion { get; set; }
        public bool cues_CuestionarioProgramado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cues_FechaHoraProgramado { get; set; }
        public int cues_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cues_FechaCreacion { get; set; }
        public int cues_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cues_FechaModificacion { get; set; }
        public bool? cues_Estado { get; set; }

        [ForeignKey(nameof(cues_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbCuestionarioscues_UsuarioCreacionNavigation))]
        public virtual tbUsuarios cues_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(cues_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbCuestionarioscues_UsuarioModificacionNavigation))]
        public virtual tbUsuarios cues_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("cues")]
        public virtual ICollection<tbPreguntasPorCuestionario> tbPreguntasPorCuestionario { get; set; }
    }
}