// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbCuestionarios
    {
        public tbCuestionarios()
        {
            tbPreguntasPorCuestionario = new HashSet<tbPreguntasPorCuestionario>();
        }

        public int cues_Id { get; set; }
        public string cues_NombreCuestionario { get; set; }
        public string cues_DescripcionCuestionario { get; set; }
        public bool cues_EsCalificado { get; set; }
        public decimal? cues_Puntuacion { get; set; }
        public bool cues_CuestionarioProgramado { get; set; }
        public DateTime? cues_FechaHoraProgramado { get; set; }
        public int cues_UsuarioCreacion { get; set; }
        public DateTime? cues_FechaCreacion { get; set; }
        public int cues_UsuarioModificacion { get; set; }
        public DateTime? cues_FechaModificacion { get; set; }
        public bool? cues_Estado { get; set; }

        public virtual tbUsuarios cues_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios cues_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPreguntasPorCuestionario> tbPreguntasPorCuestionario { get; set; }
    }
}