// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbCuestionarios
    {
        public TbCuestionarios()
        {
            TbPreguntasPorCuestionario = new HashSet<TbPreguntasPorCuestionario>();
        }

        public int CuesId { get; set; }
        public string CuesNombreCuestionario { get; set; }
        public string CuesDescripcionCuestionario { get; set; }
        public bool CuesEsCalificado { get; set; }
        public decimal? CuesPuntuacion { get; set; }
        public bool CuesCuestionarioProgramado { get; set; }
        public DateTime? CuesFechaHoraProgramado { get; set; }
        public int CuesUsuarioCreacion { get; set; }
        public DateTime? CuesFechaCreacion { get; set; }
        public int CuesUsuarioModificacion { get; set; }
        public DateTime? CuesFechaModificacion { get; set; }
        public bool? CuesEstado { get; set; }

        public virtual TbUsuarios CuesUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios CuesUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbPreguntasPorCuestionario> TbPreguntasPorCuestionario { get; set; }
    }
}