// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbDepartamentos
    {
        public TbDepartamentos()
        {
            TbMunicipios = new HashSet<TbMunicipios>();
        }

        public string DepaId { get; set; }
        public string DepaDescripcionDepartamento { get; set; }
        public int? DepaUsuarioCreacion { get; set; }
        public DateTime? DepaFechaCreacion { get; set; }
        public int? DepaUsuarioModificacion { get; set; }
        public DateTime? DepaFechaModificacion { get; set; }
        public bool? DepaEstado { get; set; }

        public virtual TbUsuarios DepaUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios DepaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbMunicipios> TbMunicipios { get; set; }
    }
}