// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbDepartamentos", Schema = "Gral")]
    [Index(nameof(depa_DescripcionDepartamento), Name = "UQ__tbDepart__EED74EF8DCF891DF", IsUnique = true)]
    [Index(nameof(depa_DescripcionDepartamento), Name = "UQ_depa_DescripcionDepartamento", IsUnique = true)]
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        [Key]
        [StringLength(2)]
        public string depa_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string depa_DescripcionDepartamento { get; set; }
        public int? depa_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? depa_FechaCreacion { get; set; }
        public int? depa_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? depa_FechaModificacion { get; set; }
        public bool? depa_Estado { get; set; }

        [ForeignKey(nameof(depa_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbDepartamentosdepa_UsuarioCreacionNavigation))]
        public virtual tbUsuarios depa_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(depa_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbDepartamentosdepa_UsuarioModificacionNavigation))]
        public virtual tbUsuarios depa_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("depa")]
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}