// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbDiscusiones
    {
        public TbDiscusiones()
        {
            TbDocumentosImagenesPorDiscusion = new HashSet<TbDocumentosImagenesPorDiscusion>();
        }

        public int DiscId { get; set; }
        public int FafeId { get; set; }
        public int OpemId { get; set; }
        public bool? DiscEsOptante { get; set; }
        public string DiscAsunto { get; set; }
        public string DiscMensaje { get; set; }
        public decimal? DiscHoras { get; set; }
        public int? DiscUsuarioCreacion { get; set; }
        public DateTime? DiscFechaCreacion { get; set; }
        public int? DiscUsuarioModificacion { get; set; }
        public DateTime? DiscFechaModificacion { get; set; }
        public bool? DiscEstado { get; set; }

        public virtual TbUsuarios DiscUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios DiscUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDocumentosImagenesPorDiscusion> TbDocumentosImagenesPorDiscusion { get; set; }
    }
}