// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbDiscusiones
    {
        public tbDiscusiones()
        {
            tbDocumentosImagenesPorDiscusion = new HashSet<tbDocumentosImagenesPorDiscusion>();
        }

        public int disc_Id { get; set; }
        public int fafe_Id { get; set; }
        public int opem_Id { get; set; }
        public bool? disc_EsOptante { get; set; }
        public string disc_Asunto { get; set; }
        public string disc_Mensaje { get; set; }
        public decimal? disc_Horas { get; set; }
        public int? disc_UsuarioCreacion { get; set; }
        public DateTime? disc_FechaCreacion { get; set; }
        public int? disc_UsuarioModificacion { get; set; }
        public DateTime? disc_FechaModificacion { get; set; }
        public bool? disc_Estado { get; set; }

        public virtual tbUsuarios disc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios disc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosImagenesPorDiscusion> tbDocumentosImagenesPorDiscusion { get; set; }
    }
}