// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbDiscusiones", Schema = "Comn")]
    public partial class tbDiscusiones
    {
        public tbDiscusiones()
        {
            tbDocumentosImagenesPorDiscusion = new HashSet<tbDocumentosImagenesPorDiscusion>();
        }

        [Key]
        public int disc_Id { get; set; }
        public int fafe_Id { get; set; }
        public int opem_Id { get; set; }
        public bool? disc_EsOptante { get; set; }
        [Required]
        [StringLength(100)]
        public string disc_Asunto { get; set; }
        [Required]
        public string disc_Mensaje { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? disc_Horas { get; set; }
        public int? disc_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? disc_FechaCreacion { get; set; }
        public int? disc_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? disc_FechaModificacion { get; set; }
        public bool? disc_Estado { get; set; }

        [ForeignKey(nameof(disc_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbDiscusionesdisc_UsuarioCreacionNavigation))]
        public virtual tbUsuarios disc_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(disc_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbDiscusionesdisc_UsuarioModificacionNavigation))]
        public virtual tbUsuarios disc_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("disc")]
        public virtual ICollection<tbDocumentosImagenesPorDiscusion> tbDocumentosImagenesPorDiscusion { get; set; }
    }
}