// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbDocumentosOptantes", Schema = "Gest")]
    [Index(nameof(doop_Descripcion), Name = "UQ__tbDocume__E25017672BD1A582", IsUnique = true)]
    public partial class tbDocumentosOptantes
    {
        [Key]
        public int doop_Id { get; set; }
        public int tido_Id { get; set; }
        public int opta_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string doop_Descripcion { get; set; }
        public int? doop_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? doop_FechaCreacion { get; set; }
        public int? doop_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? doop_FechaModificacion { get; set; }
        public bool? doop_Estado { get; set; }

        [ForeignKey(nameof(doop_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbDocumentosOptantesdoop_UsuarioCreacionNavigation))]
        public virtual tbUsuarios doop_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(doop_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbDocumentosOptantesdoop_UsuarioModificacionNavigation))]
        public virtual tbUsuarios doop_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(opta_Id))]
        [InverseProperty(nameof(tbOptantes.tbDocumentosOptantes))]
        public virtual tbOptantes opta { get; set; }
        [ForeignKey(nameof(tido_Id))]
        [InverseProperty(nameof(tbTipoDocumento.tbDocumentosOptantes))]
        public virtual tbTipoDocumento tido { get; set; }
    }
}