// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbDocumentosOptantes
    {
        public int DoopId { get; set; }
        public int TidoId { get; set; }
        public string DoopDescripcion { get; set; }
        public int? DoopUsuarioCreacion { get; set; }
        public DateTime? DoopFechaCreacion { get; set; }
        public int? DoopUsuarioModificacion { get; set; }
        public DateTime? DoopFechaModificacion { get; set; }
        public bool? DoopEstado { get; set; }
        public int OptaId { get; set; }

        public virtual TbUsuarios DoopUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios DoopUsuarioModificacionNavigation { get; set; }
        public virtual TbOptantes Opta { get; set; }
        public virtual TbTipoDocumento Tido { get; set; }
    }
}