// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbDocumentosImagenesPorDiscusion
    {
        public int DidiId { get; set; }
        public int DiscId { get; set; }
        public string DidiDocumentoOimagen { get; set; }

        public virtual TbDiscusiones Disc { get; set; }
    }
}