// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbDocumentos", Schema = "Gest")]
    [Index(nameof(docu_Descripcion), Name = "UQ__tbDocume__9055BBD41CAF4DF0", IsUnique = true)]
    public partial class tbDocumentos
    {
        [Key]
        public int docu_Id { get; set; }
        public int tido_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string docu_Descripcion { get; set; }
        public int? docu_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? docu_FechaCreacion { get; set; }
        public int? docu_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? docu_FechaModificacion { get; set; }
        public bool? docu_Estado { get; set; }

        [ForeignKey(nameof(docu_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbDocumentosdocu_UsuarioCreacionNavigation))]
        public virtual tbUsuarios docu_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(docu_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbDocumentosdocu_UsuarioModificacionNavigation))]
        public virtual tbUsuarios docu_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(tido_Id))]
        [InverseProperty(nameof(tbTipoDocumento.tbDocumentos))]
        public virtual tbTipoDocumento tido { get; set; }
    }
}