// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbDocumentosImagenesPorDiscusion", Schema = "Comn")]
    public partial class tbDocumentosImagenesPorDiscusion
    {
        [Key]
        public int didi_Id { get; set; }
        public int disc_Id { get; set; }
        [Required]
        public string didi_DocumentoOImagen { get; set; }

        [ForeignKey(nameof(disc_Id))]
        [InverseProperty(nameof(tbDiscusiones.tbDocumentosImagenesPorDiscusion))]
        public virtual tbDiscusiones disc { get; set; }
    }
}