// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbDocumentosProyectos
    {
        public tbDocumentosProyectos()
        {
            tbDocumentosOptantes = new HashSet<tbDocumentosOptantes>();
        }

        public int dopr_Id { get; set; }
        public int pryt_Id { get; set; }
        public string dopr_Descripcion { get; set; }
        public string dopr_Documento { get; set; }
        public int dopr_UsuarioCreacion { get; set; }
        public DateTime dopr_FechaCreacion { get; set; }
        public int? dopr_UsuarioModificacion { get; set; }
        public DateTime? dopr_FechaModificacion { get; set; }
        public bool? dopr_Estado { get; set; }

        public virtual tbUsuarios dopr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios dopr_UsuarioModificacionNavigation { get; set; }
        public virtual tbProyectos pryt { get; set; }
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantes { get; set; }
    }
}