// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbDocumentosImagenesPorDiscusion
    {
        public int didi_Id { get; set; }
        public int disc_Id { get; set; }
        public string didi_DocumentoOImagen { get; set; }

        public virtual tbDiscusiones disc { get; set; }
    }
}