// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbDocumentos
    {
        public int docu_Id { get; set; }
        public int tido_Id { get; set; }
        public string docu_Descripcion { get; set; }
        public int? docu_UsuarioCreacion { get; set; }
        public DateTime? docu_FechaCreacion { get; set; }
        public int? docu_UsuarioModificacion { get; set; }
        public DateTime? docu_FechaModificacion { get; set; }
        public bool? docu_Estado { get; set; }

        public virtual tbUsuarios docu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios docu_UsuarioModificacionNavigation { get; set; }
        public virtual tbTipoDocumento tido { get; set; }
    }
}