// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbDocumentos
    {
        public int DocuId { get; set; }
        public int TidoId { get; set; }
        public string DocuDescripcion { get; set; }
        public int? DocuUsuarioCreacion { get; set; }
        public DateTime? DocuFechaCreacion { get; set; }
        public int? DocuUsuarioModificacion { get; set; }
        public DateTime? DocuFechaModificacion { get; set; }
        public bool? DocuEstado { get; set; }

        public virtual TbUsuarios DocuUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios DocuUsuarioModificacionNavigation { get; set; }
        public virtual TbTipoDocumento Tido { get; set; }
    }
}