// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbEmpresas", Schema = "Gest")]
    [Index(nameof(empr_Siglas), Name = "UQ__tbEmpres__182F21D73DCE6C28", IsUnique = true)]
    [Index(nameof(empr_DescripcionEmpresa), Name = "UQ__tbEmpres__DF23A0AC236CB952", IsUnique = true)]
    public partial class tbEmpresas
    {
        public tbEmpresas()
        {
            tbProyectos = new HashSet<tbProyectos>();
        }

        [Key]
        public int empr_Id { get; set; }
        [Required]
        [StringLength(4)]
        public string muni_Id { get; set; }
        [StringLength(150)]
        public string empr_Logo { get; set; }
        [Required]
        [StringLength(30)]
        public string empr_DescripcionEmpresa { get; set; }
        [StringLength(10)]
        public string empr_Siglas { get; set; }
        [Required]
        public string empr_DireccionExacta { get; set; }
        public int? empr_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? empr_FechaCreacion { get; set; }
        public int? empr_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? empr_FechaModificacion { get; set; }
        public bool? empr_Estado { get; set; }

        [ForeignKey(nameof(empr_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbEmpresasempr_UsuarioCreacionNavigation))]
        public virtual tbUsuarios empr_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(empr_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbEmpresasempr_UsuarioModificacionNavigation))]
        public virtual tbUsuarios empr_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(muni_Id))]
        [InverseProperty(nameof(tbMunicipios.tbEmpresas))]
        public virtual tbMunicipios muni { get; set; }
        [InverseProperty("empr")]
        public virtual ICollection<tbProyectos> tbProyectos { get; set; }
    }
}