// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbEmpleadosPorActividad", Schema = "Gest")]
    public partial class tbEmpleadosPorActividad
    {
        [Key]
        public int emac_Id { get; set; }
        public int empl_Id { get; set; }
        public int acti_Id { get; set; }

        [ForeignKey(nameof(acti_Id))]
        [InverseProperty(nameof(tbActividades.tbEmpleadosPorActividad))]
        public virtual tbActividades acti { get; set; }
        [ForeignKey(nameof(empl_Id))]
        [InverseProperty(nameof(tbEmpleados.tbEmpleadosPorActividad))]
        public virtual tbEmpleados empl { get; set; }
    }
}