// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbEmpleadosPorActividad
    {
        public int emac_Id { get; set; }
        public int empl_Id { get; set; }
        public int acti_Id { get; set; }

        public virtual tbActividades acti { get; set; }
        public virtual tbEmpleados empl { get; set; }
    }
}