// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbEmpresas
    {
        public TbEmpresas()
        {
            TbProyectos = new HashSet<TbProyectos>();
        }

        public int EmprId { get; set; }
        public string MuniId { get; set; }
        public string EmprLogo { get; set; }
        public string EmprDescripcionEmpresa { get; set; }
        public string EmprSiglas { get; set; }
        public string EmprDireccionExacta { get; set; }
        public int? EmprUsuarioCreacion { get; set; }
        public DateTime? EmprFechaCreacion { get; set; }
        public int? EmprUsuarioModificacion { get; set; }
        public DateTime? EmprFechaModificacion { get; set; }
        public bool? EmprEstado { get; set; }

        public virtual TbUsuarios EmprUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios EmprUsuarioModificacionNavigation { get; set; }
        public virtual TbMunicipios Muni { get; set; }
        public virtual ICollection<TbProyectos> TbProyectos { get; set; }
    }
}