// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
            tbEmpleadosPorActividad = new HashSet<tbEmpleadosPorActividad>();
            tbRecibos = new HashSet<tbRecibos>();
        }

        public int empl_Id { get; set; }
        public string empl_Imagen { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombres { get; set; }
        public string empl_Apellidos { get; set; }
        public string empl_Telefono { get; set; }
        public string empl_Correo { get; set; }
        public string empl_Sexo { get; set; }
        public int pust_Id { get; set; }
        public int tisa_Id { get; set; }
        public int civi_Id { get; set; }
        public string muni_Id { get; set; }
        public bool empl_EsContador { get; set; }
        public int? empl_UsuarioCreacion { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public int? empl_UsuarioModificacion { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }

        public virtual tbEstadosCiviles civi { get; set; }
        public virtual tbUsuarios empl_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios empl_UsuarioModificacionNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual tbPuestos pust { get; set; }
        public virtual tbTipoSangre tisa { get; set; }
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
        public virtual ICollection<tbEmpleadosPorActividad> tbEmpleadosPorActividad { get; set; }
        public virtual ICollection<tbRecibos> tbRecibos { get; set; }
    }
}