// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbEmpleados
    {
        public TbEmpleados()
        {
            TbComponentesPorRegionalPorEmpleado = new HashSet<TbComponentesPorRegionalPorEmpleado>();
            TbEmpleadosPorActividad = new HashSet<TbEmpleadosPorActividad>();
            TbRecibos = new HashSet<TbRecibos>();
        }

        public int EmplId { get; set; }
        public string EmplImagen { get; set; }
        public string EmplDni { get; set; }
        public string EmplNombres { get; set; }
        public string EmplApellidos { get; set; }
        public string EmplTelefono { get; set; }
        public string EmplCorreo { get; set; }
        public string EmplSexo { get; set; }
        public int PustId { get; set; }
        public int TisaId { get; set; }
        public int CiviId { get; set; }
        public string MuniId { get; set; }
        public bool EmplEsContador { get; set; }
        public int? EmplUsuarioCreacion { get; set; }
        public DateTime? EmplFechaCreacion { get; set; }
        public int? EmplUsuarioModificacion { get; set; }
        public DateTime? EmplFechaModificacion { get; set; }
        public bool? EmplEstado { get; set; }

        public virtual TbEstadosCiviles Civi { get; set; }
        public virtual TbUsuarios EmplUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios EmplUsuarioModificacionNavigation { get; set; }
        public virtual TbMunicipios Muni { get; set; }
        public virtual TbPuestos Pust { get; set; }
        public virtual TbTipoSangre Tisa { get; set; }
        public virtual ICollection<TbComponentesPorRegionalPorEmpleado> TbComponentesPorRegionalPorEmpleado { get; set; }
        public virtual ICollection<TbEmpleadosPorActividad> TbEmpleadosPorActividad { get; set; }
        public virtual ICollection<TbRecibos> TbRecibos { get; set; }
    }
}