// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbEmpleados", Schema = "Gral")]
    [Index(nameof(empl_DNI), Name = "UQ_empl_DNI", IsUnique = true)]
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
            tbEmpleadosPorActividad = new HashSet<tbEmpleadosPorActividad>();
            tbRecibos = new HashSet<tbRecibos>();
        }

        [Key]
        public int empl_Id { get; set; }
        [Required]
        public string empl_Imagen { get; set; }
        [Required]
        [StringLength(13)]
        public string empl_DNI { get; set; }
        [Required]
        [StringLength(100)]
        public string empl_Nombres { get; set; }
        [Required]
        [StringLength(100)]
        public string empl_Apellidos { get; set; }
        [Required]
        [StringLength(13)]
        public string empl_Telefono { get; set; }
        [Required]
        [StringLength(100)]
        public string empl_Correo { get; set; }
        [Required]
        [StringLength(1)]
        public string empl_Sexo { get; set; }
        public int pust_Id { get; set; }
        public int tisa_Id { get; set; }
        public int civi_Id { get; set; }
        [Required]
        [StringLength(4)]
        public string muni_Id { get; set; }
        public bool empl_EsContador { get; set; }
        public int? empl_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? empl_FechaCreacion { get; set; }
        public int? empl_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }

        [ForeignKey(nameof(civi_Id))]
        [InverseProperty(nameof(tbEstadosCiviles.tbEmpleados))]
        public virtual tbEstadosCiviles civi { get; set; }
        [ForeignKey(nameof(empl_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbEmpleadosempl_UsuarioCreacionNavigation))]
        public virtual tbUsuarios empl_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(empl_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbEmpleadosempl_UsuarioModificacionNavigation))]
        public virtual tbUsuarios empl_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(muni_Id))]
        [InverseProperty(nameof(tbMunicipios.tbEmpleados))]
        public virtual tbMunicipios muni { get; set; }
        [ForeignKey(nameof(pust_Id))]
        [InverseProperty(nameof(tbPuestos.tbEmpleados))]
        public virtual tbPuestos pust { get; set; }
        [ForeignKey(nameof(tisa_Id))]
        [InverseProperty(nameof(tbTipoSangre.tbEmpleados))]
        public virtual tbTipoSangre tisa { get; set; }
        [InverseProperty("empl")]
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
        [InverseProperty("empl")]
        public virtual ICollection<tbEmpleadosPorActividad> tbEmpleadosPorActividad { get; set; }
        [InverseProperty("empl")]
        public virtual ICollection<tbRecibos> tbRecibos { get; set; }
    }
}