// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbEmpresas
    {
        public tbEmpresas()
        {
            tbProyectos = new HashSet<tbProyectos>();
        }

        public int empr_Id { get; set; }
        public string muni_Id { get; set; }
        public string empr_Logo { get; set; }
        public string empr_DescripcionEmpresa { get; set; }
        public string empr_Siglas { get; set; }
        public string empr_DireccionExacta { get; set; }
        public int? empr_UsuarioCreacion { get; set; }
        public DateTime? empr_FechaCreacion { get; set; }
        public int? empr_UsuarioModificacion { get; set; }
        public DateTime? empr_FechaModificacion { get; set; }
        public bool? empr_Estado { get; set; }

        public virtual tbUsuarios empr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios empr_UsuarioModificacionNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbProyectos> tbProyectos { get; set; }
    }
}