// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbEstadosCiviles
    {
        public TbEstadosCiviles()
        {
            TbEmpleados = new HashSet<TbEmpleados>();
            TbOptantes = new HashSet<TbOptantes>();
        }

        public int CiviId { get; set; }
        public string CiviDescripcionEstadoCivil { get; set; }
        public int? CiviUsuarioCreacion { get; set; }
        public DateTime? CiviFechaCreacion { get; set; }
        public int? CiviUsuarioModificacion { get; set; }
        public DateTime? CiviFechaModificacion { get; set; }
        public bool? CiviEstado { get; set; }

        public virtual TbUsuarios CiviUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios CiviUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleados { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
    }
}