// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbEstadosCiviles", Schema = "Gral")]
    [Index(nameof(civi_DescripcionEstadoCivil), Name = "UQ__tbEstado__2DAB6DA82038D3F7", IsUnique = true)]
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbOptantes = new HashSet<tbOptantes>();
        }

        [Key]
        public int civi_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string civi_DescripcionEstadoCivil { get; set; }
        public int? civi_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? civi_FechaCreacion { get; set; }
        public int? civi_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? civi_FechaModificacion { get; set; }
        public bool? civi_Estado { get; set; }

        [ForeignKey(nameof(civi_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbEstadosCivilescivi_UsuarioCreacionNavigation))]
        public virtual tbUsuarios civi_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(civi_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbEstadosCivilescivi_UsuarioModificacionNavigation))]
        public virtual tbUsuarios civi_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("civi")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        [InverseProperty("civi")]
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}