// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbFacultadPorRegional
    {
        public tbFacultadPorRegional()
        {
            tbCarreraPorFacultadPorRegional = new HashSet<tbCarreraPorFacultadPorRegional>();
        }

        public int fare_Id { get; set; }
        public int facu_Id { get; set; }
        public int regi_Id { get; set; }

        public virtual tbFacultades facu { get; set; }
        public virtual tbRegionales regi { get; set; }
        public virtual ICollection<tbCarreraPorFacultadPorRegional> tbCarreraPorFacultadPorRegional { get; set; }
    }
}