// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbFacultadPorRegional
    {
        public TbFacultadPorRegional()
        {
            TbCarreraPorFacultadPorRegional = new HashSet<TbCarreraPorFacultadPorRegional>();
        }

        public int FareId { get; set; }
        public int FacuId { get; set; }
        public int RegiId { get; set; }

        public virtual TbFacultades Facu { get; set; }
        public virtual TbRegionales Regi { get; set; }
        public virtual ICollection<TbCarreraPorFacultadPorRegional> TbCarreraPorFacultadPorRegional { get; set; }
    }
}