// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbFacultades", Schema = "Gral")]
    [Index(nameof(facu_DesripcionFacultad), Name = "UQ_tbFacultades_facu_DesripcionFacultad", IsUnique = true)]
    public partial class tbFacultades
    {
        public tbFacultades()
        {
            tbFacultadPorRegional = new HashSet<tbFacultadPorRegional>();
        }

        [Key]
        public int facu_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string facu_DesripcionFacultad { get; set; }
        public int? facu_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? facu_FechaCreacion { get; set; }
        public int? facu_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? facu_FechaModificacion { get; set; }
        public bool? facu_Estado { get; set; }

        [ForeignKey(nameof(facu_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbFacultadesfacu_UsuarioCreacionNavigation))]
        public virtual tbUsuarios facu_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(facu_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbFacultadesfacu_UsuarioModificacionNavigation))]
        public virtual tbUsuarios facu_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("facu")]
        public virtual ICollection<tbFacultadPorRegional> tbFacultadPorRegional { get; set; }
    }
}