// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbFacultadPorRegional", Schema = "Gral")]
    public partial class tbFacultadPorRegional
    {
        public tbFacultadPorRegional()
        {
            tbCarreraPorFacultadPorRegional = new HashSet<tbCarreraPorFacultadPorRegional>();
        }

        [Key]
        public int fare_Id { get; set; }
        public int facu_Id { get; set; }
        public int regi_Id { get; set; }

        [ForeignKey(nameof(facu_Id))]
        [InverseProperty(nameof(tbFacultades.tbFacultadPorRegional))]
        public virtual tbFacultades facu { get; set; }
        [ForeignKey(nameof(regi_Id))]
        [InverseProperty(nameof(tbRegionales.tbFacultadPorRegional))]
        public virtual tbRegionales regi { get; set; }
        [InverseProperty("fare")]
        public virtual ICollection<tbCarreraPorFacultadPorRegional> tbCarreraPorFacultadPorRegional { get; set; }
    }
}