// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbFacultades
    {
        public TbFacultades()
        {
            TbFacultadPorRegional = new HashSet<TbFacultadPorRegional>();
        }

        public int FacuId { get; set; }
        public string FacuDesripcionFacultad { get; set; }
        public int? FacuUsuarioCreacion { get; set; }
        public DateTime? FacuFechaCreacion { get; set; }
        public int? FacuUsuarioModificacion { get; set; }
        public DateTime? FacuFechaModificacion { get; set; }
        public bool? FacuEstado { get; set; }

        public virtual TbUsuarios FacuUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios FacuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbFacultadPorRegional> TbFacultadPorRegional { get; set; }
    }
}