// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbFacultades
    {
        public tbFacultades()
        {
            tbFacultadPorRegional = new HashSet<tbFacultadPorRegional>();
        }

        public int facu_Id { get; set; }
        public int fare_Id { get; set; }
        public string facu_DesripcionFacultad { get; set; }
        public int? facu_UsuarioCreacion { get; set; }
        public DateTime? facu_FechaCreacion { get; set; }
        public int? facu_UsuarioModificacion { get; set; }
        public DateTime? facu_FechaModificacion { get; set; }
        public bool? facu_Estado { get; set; }

        public virtual tbUsuarios facu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios facu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacultadPorRegional> tbFacultadPorRegional { get; set; }
    }
}