// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbForosPorActividad
    {
        public int FoacId { get; set; }
        public int ForoId { get; set; }
        public int? ActiId { get; set; }
        public int? CompId { get; set; }
        public bool FoacForoProgramado { get; set; }
        public bool? FoacOtorgaHoras { get; set; }
        public string FoacDescripcion { get; set; }
        public TimeSpan? FoacHoras { get; set; }
        public DateTime? FoacFechaHoraProgramado { get; set; }
        public int? FoacUsuarioCreacion { get; set; }
        public DateTime? FoacFechaCreacion { get; set; }
        public int? FoacUsuarioModificacion { get; set; }
        public DateTime? FoacFechaModificacion { get; set; }
        public bool? FoacEstado { get; set; }

        public virtual TbActividades Acti { get; set; }
        public virtual TbComponentes Comp { get; set; }
        public virtual TbUsuarios FoacUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios FoacUsuarioModificacionNavigation { get; set; }
        public virtual TbForos Foro { get; set; }
    }
}