// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbForos", Schema = "Comn")]
    public partial class tbForos
    {
        public tbForos()
        {
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
            tbForosPorEmpleados = new HashSet<tbForosPorEmpleados>();
        }

        [Key]
        public int foro_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string foro_Titulo { get; set; }
        public bool foro_EsNacional { get; set; }
        public bool foro_EsParaEmpleados { get; set; }
        public int? foro_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? foro_FechaCreacion { get; set; }
        public int? foro_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? foro_FechaModificacion { get; set; }
        public bool? foro_Estado { get; set; }

        [ForeignKey(nameof(foro_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbForosforo_UsuarioCreacionNavigation))]
        public virtual tbUsuarios foro_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(foro_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbForosforo_UsuarioModificacionNavigation))]
        public virtual tbUsuarios foro_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("foro")]
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
        [InverseProperty("foro")]
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleados { get; set; }
    }
}