// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbForosPorActividad
    {
        public int foac_Id { get; set; }
        public int foro_Id { get; set; }
        public int? acti_Id { get; set; }
        public int? comp_Id { get; set; }
        public bool foac_ForoProgramado { get; set; }
        public bool? foac_OtorgaHoras { get; set; }
        public string foac_Descripcion { get; set; }
        public TimeSpan? foac_Horas { get; set; }
        public DateTime? foac_FechaHoraProgramado { get; set; }
        public int? foac_UsuarioCreacion { get; set; }
        public DateTime? foac_FechaCreacion { get; set; }
        public int? foac_UsuarioModificacion { get; set; }
        public DateTime? foac_FechaModificacion { get; set; }
        public bool? foac_Estado { get; set; }

        public virtual tbActividades acti { get; set; }
        public virtual tbComponentes comp { get; set; }
        public virtual tbUsuarios foac_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios foac_UsuarioModificacionNavigation { get; set; }
        public virtual tbForos foro { get; set; }
    }
}