// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbForosPorEmpleados
    {
        public int FoemId { get; set; }
        public int ForoId { get; set; }
        public string FoemDescripcion { get; set; }
        public bool FoemForoProgramado { get; set; }
        public DateTime? FoemFechaHoraProgramado { get; set; }
        public int? FoemUsuarioCreacion { get; set; }
        public DateTime? FoemFechaCreacion { get; set; }
        public int? FoemUsuarioModificacion { get; set; }
        public DateTime? FoemFechaModificacion { get; set; }
        public bool? FoemEstado { get; set; }

        public virtual TbUsuarios FoemUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios FoemUsuarioModificacionNavigation { get; set; }
        public virtual TbForos Foro { get; set; }
    }
}