// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbForos
    {
        public TbForos()
        {
            TbForosPorActividad = new HashSet<TbForosPorActividad>();
            TbForosPorEmpleados = new HashSet<TbForosPorEmpleados>();
        }

        public int ForoId { get; set; }
        public string ForoTitulo { get; set; }
        public bool ForoEsNacional { get; set; }
        public bool ForoEsParaEmpleados { get; set; }
        public int? ForoUsuarioCreacion { get; set; }
        public DateTime? ForoFechaCreacion { get; set; }
        public int? ForoUsuarioModificacion { get; set; }
        public DateTime? ForoFechaModificacion { get; set; }
        public bool? ForoEstado { get; set; }

        public virtual TbUsuarios ForoUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios ForoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbForosPorActividad> TbForosPorActividad { get; set; }
        public virtual ICollection<TbForosPorEmpleados> TbForosPorEmpleados { get; set; }
    }
}