// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbForos
    {
        public tbForos()
        {
            tbForosPorActividad = new HashSet<tbForosPorActividad>();
            tbForosPorEmpleados = new HashSet<tbForosPorEmpleados>();
        }

        public int foro_Id { get; set; }
        public string foro_Titulo { get; set; }
        public bool foro_EsNacional { get; set; }
        public bool foro_EsParaEmpleados { get; set; }
        public int? foro_UsuarioCreacion { get; set; }
        public DateTime? foro_FechaCreacion { get; set; }
        public int? foro_UsuarioModificacion { get; set; }
        public DateTime? foro_FechaModificacion { get; set; }
        public bool? foro_Estado { get; set; }

        public virtual tbUsuarios foro_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios foro_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbForosPorActividad> tbForosPorActividad { get; set; }
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleados { get; set; }
    }
}