// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbHojaTiempoPorOptanteBitacora
    {
        public string HotoAccion { get; set; }
        public int? HotoId { get; set; }
        public int? HotiId { get; set; }
        public int? OptaId { get; set; }
        public decimal? HotoHorasTotalesRealizadas { get; set; }
        public string OtoComentario { get; set; }
        public DateTime? HotoFechaHoraEntrega { get; set; }
        public bool? HotiAprobada { get; set; }
        public int? HotoUsuarioCreacion { get; set; }
        public DateTime? HotoFechaCreacion { get; set; }
        public int? HotoUsuarioModificacion { get; set; }
        public DateTime? HotoFechaModificacion { get; set; }
        public int? HotoUsuarioEliminado { get; set; }
        public DateTime? HotoFechaEliminado { get; set; }
        public bool? HotoEstado { get; set; }
    }
}