// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbHojaTiempo", Schema = "Gest")]
    public partial class tbHojaTiempo
    {
        public tbHojaTiempo()
        {
            tbHojaTiempoPorOptante = new HashSet<tbHojaTiempoPorOptante>();
        }

        [Key]
        public int hoti_Id { get; set; }
        public int comp_Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime hoti_PeriodoInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? hoti_PeriodoFinal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime hoti_FechaHoraEntregaLimite { get; set; }
        public TimeSpan? hoti_HorasMinimas { get; set; }
        public int? hoti_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoti_FechaCreacion { get; set; }
        public int? hoti_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoti_FechaModificacion { get; set; }
        public bool? hoti_Estado { get; set; }

        [ForeignKey(nameof(comp_Id))]
        [InverseProperty(nameof(tbComponentes.tbHojaTiempo))]
        public virtual tbComponentes comp { get; set; }
        [ForeignKey(nameof(hoti_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbHojaTiempohoti_UsuarioCreacionNavigation))]
        public virtual tbUsuarios hoti_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(hoti_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbHojaTiempohoti_UsuarioModificacionNavigation))]
        public virtual tbUsuarios hoti_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("hoti")]
        public virtual ICollection<tbHojaTiempoPorOptante> tbHojaTiempoPorOptante { get; set; }
    }
}