// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbHojaTiempo
    {
        public TbHojaTiempo()
        {
            TbHojaTiempoPorOptante = new HashSet<TbHojaTiempoPorOptante>();
        }

        public int HotiId { get; set; }
        public int CompId { get; set; }
        public DateTime HotiPeriodoInicio { get; set; }
        public DateTime? HotiPeriodoFinal { get; set; }
        public DateTime HotiFechaHoraEntregaLimite { get; set; }
        public int? HotiUsuarioCreacion { get; set; }
        public DateTime? HotiFechaCreacion { get; set; }
        public int? HotiUsuarioModificacion { get; set; }
        public DateTime? HotiFechaModificacion { get; set; }
        public bool? HotiEstado { get; set; }
        public TimeSpan? HotiHorasMinimas { get; set; }

        public virtual TbComponentes Comp { get; set; }
        public virtual TbUsuarios HotiUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios HotiUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbHojaTiempoPorOptante> TbHojaTiempoPorOptante { get; set; }
    }
}