// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Keyless]
    [Table("tbHojaTiempoPorOptanteBitacora", Schema = "Gest")]
    public partial class tbHojaTiempoPorOptanteBitacora
    {
        [StringLength(1)]
        public string hoto_Accion { get; set; }
        public int? hoto_Id { get; set; }
        public int? hoti_Id { get; set; }
        public int? opta_Id { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? hoto_HorasTotalesRealizadas { get; set; }
        [StringLength(250)]
        public string oto_Comentario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoto_FechaHoraEntrega { get; set; }
        public bool? hoti_Aprobada { get; set; }
        public int? hoto_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoto_FechaCreacion { get; set; }
        public int? hoto_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoto_FechaModificacion { get; set; }
        public int? hoto_UsuarioEliminado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hoto_FechaEliminado { get; set; }
        public bool? hoto_Estado { get; set; }
    }
}