// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbModulosPorRoles
    {
        public int moro_Id { get; set; }
        public int modu_Id { get; set; }
        public int role_Id { get; set; }

        public virtual tbModulos modu { get; set; }
        public virtual tbRoles role { get; set; }
    }
}