// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbModulosPorRoles
    {
        public int MoroId { get; set; }
        public int ModuId { get; set; }
        public int RoleId { get; set; }

        public virtual TbModulos Modu { get; set; }
        public virtual TbRoles Role { get; set; }
    }
}