// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbModulosPorRoles", Schema = "Accs")]
    public partial class tbModulosPorRoles
    {
        [Key]
        public int moro_Id { get; set; }
        public int modu_Id { get; set; }
        public int role_Id { get; set; }

        [ForeignKey(nameof(modu_Id))]
        [InverseProperty(nameof(tbModulos.tbModulosPorRoles))]
        public virtual tbModulos modu { get; set; }
        [ForeignKey(nameof(role_Id))]
        [InverseProperty(nameof(tbRoles.tbModulosPorRoles))]
        public virtual tbRoles role { get; set; }
    }
}