// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbModulos
    {
        public TbModulos()
        {
            TbModulosPorRoles = new HashSet<TbModulosPorRoles>();
        }

        public int ModuId { get; set; }
        public string ModuDescripcionModulo { get; set; }
        public string ModuUrlModulo { get; set; }
        public int? ModuUsuarioCreacion { get; set; }
        public DateTime? ModuFechaCreacion { get; set; }
        public int? ModuUsuarioModificacion { get; set; }
        public DateTime? ModuFechaModificacion { get; set; }
        public bool? ModuEstado { get; set; }

        public virtual TbUsuarios ModuUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios ModuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbModulosPorRoles> TbModulosPorRoles { get; set; }
    }
}