// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbActividades = new HashSet<tbActividades>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbEmpresas = new HashSet<tbEmpresas>();
            tbOptantes = new HashSet<tbOptantes>();
            tbRegionalCorporativa = new HashSet<tbRegionalCorporativa>();
            tbRegionales = new HashSet<tbRegionales>();
        }

        public string muni_Id { get; set; }
        public string depa_Id { get; set; }
        public string muni_DescripcionMunicipio { get; set; }
        public int? muni_UsuarioCreacion { get; set; }
        public DateTime? muni_FechaCreacion { get; set; }
        public int? muni_UsuarioModificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool? muni_Estado { get; set; }

        public virtual tbDepartamentos depa { get; set; }
        public virtual tbUsuarios muni_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios muni_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividades { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresas { get; set; }
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativa { get; set; }
        public virtual ICollection<tbRegionales> tbRegionales { get; set; }
    }
}