// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbMunicipios", Schema = "Gral")]
    [Index(nameof(muni_DescripcionMunicipio), Name = "UQ__tbMunici__34A349564A3D2700", IsUnique = true)]
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbActividades = new HashSet<tbActividades>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbEmpresas = new HashSet<tbEmpresas>();
            tbOptantes = new HashSet<tbOptantes>();
            tbRegionalCorporativa = new HashSet<tbRegionalCorporativa>();
            tbRegionales = new HashSet<tbRegionales>();
        }

        [Key]
        [StringLength(4)]
        public string muni_Id { get; set; }
        [Required]
        [StringLength(2)]
        public string depa_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string muni_DescripcionMunicipio { get; set; }
        public int? muni_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? muni_FechaCreacion { get; set; }
        public int? muni_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? muni_FechaModificacion { get; set; }
        public bool? muni_Estado { get; set; }

        [ForeignKey(nameof(depa_Id))]
        [InverseProperty(nameof(tbDepartamentos.tbMunicipios))]
        public virtual tbDepartamentos depa { get; set; }
        [ForeignKey(nameof(muni_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbMunicipiosmuni_UsuarioCreacionNavigation))]
        public virtual tbUsuarios muni_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(muni_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbMunicipiosmuni_UsuarioModificacionNavigation))]
        public virtual tbUsuarios muni_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbActividades> tbActividades { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbEmpresas> tbEmpresas { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativa { get; set; }
        [InverseProperty("muni")]
        public virtual ICollection<tbRegionales> tbRegionales { get; set; }
    }
}