// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbMunicipios
    {
        public TbMunicipios()
        {
            TbActividades = new HashSet<TbActividades>();
            TbEmpleados = new HashSet<TbEmpleados>();
            TbEmpresas = new HashSet<TbEmpresas>();
            TbOptantes = new HashSet<TbOptantes>();
            TbRegionalCorporativa = new HashSet<TbRegionalCorporativa>();
            TbRegionales = new HashSet<TbRegionales>();
        }

        public string MuniId { get; set; }
        public string DepaId { get; set; }
        public string MuniDescripcionMunicipio { get; set; }
        public int? MuniUsuarioCreacion { get; set; }
        public DateTime? MuniFechaCreacion { get; set; }
        public int? MuniUsuarioModificacion { get; set; }
        public DateTime? MuniFechaModificacion { get; set; }
        public bool? MuniEstado { get; set; }

        public virtual TbDepartamentos Depa { get; set; }
        public virtual TbUsuarios MuniUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios MuniUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbActividades> TbActividades { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleados { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresas { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
        public virtual ICollection<TbRegionalCorporativa> TbRegionalCorporativa { get; set; }
        public virtual ICollection<TbRegionales> TbRegionales { get; set; }
    }
}