// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbNotificacionesPorUsuario
    {
        public int NapuId { get; set; }
        public int UsuaId { get; set; }
        public bool NapuAlertaOnoti { get; set; }
        public int NapuAlertaOnotiId { get; set; }
        public string NapuRuta { get; set; }
        public bool NapuLeida { get; set; }
        public int NapuUsuarioCreacion { get; set; }
        public DateTime NapuFechaCreacion { get; set; }
        public int? NapuUsuarioModificacion { get; set; }
        public DateTime? NapuFechaModificacion { get; set; }
        public bool NapuEstado { get; set; }

        public virtual TbUsuarios NapuUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios NapuUsuarioModificacionNavigation { get; set; }
        public virtual TbUsuarios Usua { get; set; }
    }
}