// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbNotificaciones
    {
        public int NotiId { get; set; }
        public string NotiDescripcion { get; set; }
        public DateTime NotiFecha { get; set; }
        public string NotiRuta { get; set; }
        public int NotiUsuarioCreacion { get; set; }
        public DateTime NotiFechaCreacion { get; set; }
        public int? NotiUsuarioModificacion { get; set; }
        public DateTime? NotiFechaModificacion { get; set; }
        public bool? NotiEstado { get; set; }

        public virtual TbUsuarios NotiUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios NotiUsuarioModificacionNavigation { get; set; }
    }
}