// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbNotificaciones
    {
        public int noti_Id { get; set; }
        public string noti_Descripcion { get; set; }
        public DateTime noti_Fecha { get; set; }
        public string noti_Ruta { get; set; }
        public int noti_UsuarioCreacion { get; set; }
        public DateTime noti_FechaCreacion { get; set; }
        public int? noti_UsuarioModificacion { get; set; }
        public DateTime? noti_FechaModificacion { get; set; }
        public bool? noti_Estado { get; set; }

        public virtual tbUsuarios noti_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios noti_UsuarioModificacionNavigation { get; set; }
    }
}