// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbNotificacionesPorUsuario
    {
        public int napu_Id { get; set; }
        public int usua_Id { get; set; }
        public bool napu_AlertaOnoti { get; set; }
        public int napu_AlertaONoti_Id { get; set; }
        public string napu_Ruta { get; set; }
        public bool napu_Leida { get; set; }
        public int napu_UsuarioCreacion { get; set; }
        public DateTime napu_FechaCreacion { get; set; }
        public int? napu_UsuarioModificacion { get; set; }
        public DateTime? napu_FechaModificacion { get; set; }
        public bool napu_Estado { get; set; }

        public virtual tbUsuarios napu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios napu_UsuarioModificacionNavigation { get; set; }
        public virtual tbUsuarios usua { get; set; }
    }
}