// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbNotificacionesPorUsuario", Schema = "Comn")]
    public partial class tbNotificacionesPorUsuario
    {
        [Key]
        public int napu_Id { get; set; }
        public int usua_Id { get; set; }
        public bool napu_AlertaOnoti { get; set; }
        public int napu_AlertaONoti_Id { get; set; }
        [StringLength(50)]
        public string napu_Ruta { get; set; }
        public bool napu_Leida { get; set; }
        public int napu_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime napu_FechaCreacion { get; set; }
        public int? napu_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? napu_FechaModificacion { get; set; }
        public bool napu_Estado { get; set; }

        [ForeignKey(nameof(napu_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbNotificacionesPorUsuarionapu_UsuarioCreacionNavigation))]
        public virtual tbUsuarios napu_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(napu_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbNotificacionesPorUsuarionapu_UsuarioModificacionNavigation))]
        public virtual tbUsuarios napu_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(usua_Id))]
        [InverseProperty(nameof(tbUsuarios.tbNotificacionesPorUsuariousua))]
        public virtual tbUsuarios usua { get; set; }
    }
}