// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbNotificaciones", Schema = "Comn")]
    public partial class tbNotificaciones
    {
        [Key]
        public int noti_Id { get; set; }
        [Required]
        public string noti_Descripcion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime noti_Fecha { get; set; }
        [Required]
        [StringLength(50)]
        public string noti_Ruta { get; set; }
        public int noti_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime noti_FechaCreacion { get; set; }
        public int? noti_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? noti_FechaModificacion { get; set; }
        public bool? noti_Estado { get; set; }

        [ForeignKey(nameof(noti_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbNotificacionesnoti_UsuarioCreacionNavigation))]
        public virtual tbUsuarios noti_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(noti_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbNotificacionesnoti_UsuarioModificacionNavigation))]
        public virtual tbUsuarios noti_UsuarioModificacionNavigation { get; set; }
    }
}