// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbOptantes
    {
        public TbOptantes()
        {
            TbActividadesPorOptante = new HashSet<TbActividadesPorOptante>();
            TbBeneficiosPorOptante = new HashSet<TbBeneficiosPorOptante>();
            TbDocumentosOptantes = new HashSet<TbDocumentosOptantes>();
            TbHojaTiempoPorOptante = new HashSet<TbHojaTiempoPorOptante>();
            TbRecibosPorOptante = new HashSet<TbRecibosPorOptante>();
            TbRespuestasPorOptante = new HashSet<TbRespuestasPorOptante>();
        }

        public int OptaId { get; set; }
        public string OptaImagen { get; set; }
        public string OptaDni { get; set; }
        public string OptaPrimerNombre { get; set; }
        public string OptaSegundoNombre { get; set; }
        public string OptaPrimerApellido { get; set; }
        public string OptaSegundoApellido { get; set; }
        public string OptaSexo { get; set; }
        public string OptaDireccion { get; set; }
        public string OptaCorreoElectronico { get; set; }
        public string OptaTelefono1 { get; set; }
        public string OptaTelefono2 { get; set; }
        public DateTime? OptaFechaInicio { get; set; }
        public DateTime? OptaFechaFin { get; set; }
        public string OptaObservacion { get; set; }
        public int? CompId { get; set; }
        public int CiviId { get; set; }
        public int TisaId { get; set; }
        public string MuniId { get; set; }
        public int CafrId { get; set; }
        public int? BancId { get; set; }
        public bool? OptaTipoPago { get; set; }
        public string OptaCuentaBancaria { get; set; }
        public bool OptaOptanteAceptado { get; set; }
        public int? OptaUsuarioCreacion { get; set; }
        public DateTime? OptaFechaCreacion { get; set; }
        public int? OptaUsuarioModificacion { get; set; }
        public DateTime? OptaFechamodificacion { get; set; }
        public bool? OptaEstado { get; set; }

        public virtual TbBancos Banc { get; set; }
        public virtual TbCarreraPorFacultadPorRegional Cafr { get; set; }
        public virtual TbEstadosCiviles Civi { get; set; }
        public virtual TbComponentes Comp { get; set; }
        public virtual TbMunicipios Muni { get; set; }
        public virtual TbUsuarios OptaUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios OptaUsuarioModificacionNavigation { get; set; }
        public virtual TbTipoSangre Tisa { get; set; }
        public virtual ICollection<TbActividadesPorOptante> TbActividadesPorOptante { get; set; }
        public virtual ICollection<TbBeneficiosPorOptante> TbBeneficiosPorOptante { get; set; }
        public virtual ICollection<TbDocumentosOptantes> TbDocumentosOptantes { get; set; }
        public virtual ICollection<TbHojaTiempoPorOptante> TbHojaTiempoPorOptante { get; set; }
        public virtual ICollection<TbRecibosPorOptante> TbRecibosPorOptante { get; set; }
        public virtual ICollection<TbRespuestasPorOptante> TbRespuestasPorOptante { get; set; }
    }
}