// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbOpcionesPorPregunta
    {
        public TbOpcionesPorPregunta()
        {
            TbRespuestasPorOptante = new HashSet<TbRespuestasPorOptante>();
        }

        public int OpprId { get; set; }
        public int PrcuId { get; set; }
        public string OpprNombreOpcion { get; set; }
        public bool OpprEsRespuesta { get; set; }

        public virtual TbPreguntasPorCuestionario Prcu { get; set; }
        public virtual ICollection<TbRespuestasPorOptante> TbRespuestasPorOptante { get; set; }
    }
}