// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Keyless]
    [Table("tbOptantesBitacora", Schema = "Gest")]
    public partial class tbOptantesBitacora
    {
        [StringLength(1)]
        public string opta_Accion { get; set; }
        public int? opta_Id { get; set; }
        public string opta_Imagen { get; set; }
        [StringLength(15)]
        public string opta_DNI { get; set; }
        [StringLength(20)]
        public string opta_PrimerNombre { get; set; }
        [StringLength(20)]
        public string opta_SegundoNombre { get; set; }
        [StringLength(20)]
        public string opta_PrimerApellido { get; set; }
        [StringLength(20)]
        public string opta_SegundoApellido { get; set; }
        [StringLength(1)]
        public string opta_Sexo { get; set; }
        [StringLength(50)]
        public string opta_Direccion { get; set; }
        [StringLength(60)]
        public string opta_CorreoElectronico { get; set; }
        [StringLength(9)]
        public string opta_Telefono1 { get; set; }
        [StringLength(9)]
        public string opta_Telefono2 { get; set; }
        [Column(TypeName = "date")]
        public DateTime? opta_FechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? opta_FechaFin { get; set; }
        public string opta_Observacion { get; set; }
        public int? comp_Id { get; set; }
        public int? civi_Id { get; set; }
        public int? tisa_Id { get; set; }
        [StringLength(4)]
        public string muni_Id { get; set; }
        public int? cafr_Id { get; set; }
        public int? banc_Id { get; set; }
        public bool? opta_TipoPago { get; set; }
        [StringLength(30)]
        public string opta_CuentaBancaria { get; set; }
        public bool? opta_OptanteAceptado { get; set; }
        public int? opta_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? opta_FechaCreacion { get; set; }
        public int? opta_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? opta_Fechamodificacion { get; set; }
        public int? opta_UsuarioEliminado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? opta_FechaEliminado { get; set; }
        public bool? opta_Estado { get; set; }
    }
}