// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbOptantesBitacora
    {
        public string OptaAccion { get; set; }
        public int? OptaId { get; set; }
        public string OptaImagen { get; set; }
        public string OptaDni { get; set; }
        public string OptaPrimerNombre { get; set; }
        public string OptaSegundoNombre { get; set; }
        public string OptaPrimerApellido { get; set; }
        public string OptaSegundoApellido { get; set; }
        public string OptaSexo { get; set; }
        public string OptaDireccion { get; set; }
        public string OptaCorreoElectronico { get; set; }
        public string OptaTelefono1 { get; set; }
        public string OptaTelefono2 { get; set; }
        public DateTime? OptaFechaInicio { get; set; }
        public DateTime? OptaFechaFin { get; set; }
        public string OptaObservacion { get; set; }
        public int? CompId { get; set; }
        public int? CiviId { get; set; }
        public int? TisaId { get; set; }
        public string MuniId { get; set; }
        public int? CafrId { get; set; }
        public int? BancId { get; set; }
        public bool? OptaTipoPago { get; set; }
        public string OptaCuentaBancaria { get; set; }
        public bool? OptaOptanteAceptado { get; set; }
        public int? OptaUsuarioCreacion { get; set; }
        public DateTime? OptaFechaCreacion { get; set; }
        public int? OptaUsuarioModificacion { get; set; }
        public DateTime? OptaFechamodificacion { get; set; }
        public int? OptaUsuarioEliminado { get; set; }
        public DateTime? OptaFechaEliminado { get; set; }
        public bool? OptaEstado { get; set; }
    }
}