// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbOpcionesPorPregunta", Schema = "Gest")]
    public partial class tbOpcionesPorPregunta
    {
        public tbOpcionesPorPregunta()
        {
            tbRespuestasPorOptante = new HashSet<tbRespuestasPorOptante>();
        }

        [Key]
        public int oppr_Id { get; set; }
        public int prcu_Id { get; set; }
        [Required]
        public string oppr_NombreOpcion { get; set; }
        public bool oppr_EsRespuesta { get; set; }

        [ForeignKey(nameof(prcu_Id))]
        [InverseProperty(nameof(tbPreguntasPorCuestionario.tbOpcionesPorPregunta))]
        public virtual tbPreguntasPorCuestionario prcu { get; set; }
        [InverseProperty("oppr")]
        public virtual ICollection<tbRespuestasPorOptante> tbRespuestasPorOptante { get; set; }
    }
}