// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbOpcionesPorPregunta
    {
        public tbOpcionesPorPregunta()
        {
            tbRespuestasPorOptante = new HashSet<tbRespuestasPorOptante>();
        }

        public int oppr_Id { get; set; }
        public int prcu_Id { get; set; }
        public string oppr_NombreOpcion { get; set; }
        public bool oppr_EsRespuesta { get; set; }

        public virtual tbPreguntasPorCuestionario prcu { get; set; }
        public virtual ICollection<tbRespuestasPorOptante> tbRespuestasPorOptante { get; set; }
    }
}