// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbPreguntasFrecuentes
    {
        public int prfr_Id { get; set; }
        public string prfr_Pregunta { get; set; }
        public string prfr_Respuesta { get; set; }
        public int? prfr_UsuarioCreacion { get; set; }
        public DateTime? prfr_FechaCreacion { get; set; }
        public int? prfr_UsuarioModificacion { get; set; }
        public DateTime? prfr_FechaModificacion { get; set; }
        public bool? prfr_Estado { get; set; }

        public virtual tbUsuarios prfr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios prfr_UsuarioModificacionNavigation { get; set; }
    }
}