// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbProyectos
    {
        public TbProyectos()
        {
            TbComponentes = new HashSet<TbComponentes>();
        }

        public int PrytId { get; set; }
        public string PrytDescripcionProyecto { get; set; }
        public decimal? PrytHorasProceso { get; set; }
        public int EmprId { get; set; }
        public int? PrytUsuarioCreacion { get; set; }
        public DateTime? PrytFechaCreacion { get; set; }
        public int? PrytUsuarioModificacion { get; set; }
        public DateTime? PrytFechaModificacion { get; set; }
        public bool? PrytEstado { get; set; }

        public virtual TbEmpresas Empr { get; set; }
        public virtual TbUsuarios PrytUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios PrytUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbComponentes> TbComponentes { get; set; }
    }
}