// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbPreguntasFrecuentes
    {
        public int PrfrId { get; set; }
        public string PrfrPregunta { get; set; }
        public string PrfrRespuesta { get; set; }
        public int? PrfrUsuarioCreacion { get; set; }
        public DateTime? PrfrFechaCreacion { get; set; }
        public int? PrfrUsuarioModificacion { get; set; }
        public DateTime? PrfrFechaModificacion { get; set; }
        public bool? PrfrEstado { get; set; }

        public virtual TbUsuarios PrfrUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios PrfrUsuarioModificacionNavigation { get; set; }
    }
}