// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbPreguntasPorCuestionario
    {
        public TbPreguntasPorCuestionario()
        {
            TbOpcionesPorPregunta = new HashSet<TbOpcionesPorPregunta>();
        }

        public int PrcuId { get; set; }
        public int CuesId { get; set; }
        public bool PrcuEsRespuestaBreve { get; set; }
        public string PrcuPregunta { get; set; }
        public decimal? PrcuPuntuacion { get; set; }

        public virtual TbCuestionarios Cues { get; set; }
        public virtual ICollection<TbOpcionesPorPregunta> TbOpcionesPorPregunta { get; set; }
    }
}