// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbPreguntasFrecuentes", Schema = "Comn")]
    [Index(nameof(prfr_Pregunta), Name = "UQ_tbPreguntasFrecuentes_prfr_Pregunta", IsUnique = true)]
    public partial class tbPreguntasFrecuentes
    {
        [Key]
        public int prfr_Id { get; set; }
        [Required]
        [StringLength(200)]
        public string prfr_Pregunta { get; set; }
        [Required]
        public string prfr_Respuesta { get; set; }
        public int? prfr_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prfr_FechaCreacion { get; set; }
        public int? prfr_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prfr_FechaModificacion { get; set; }
        public bool? prfr_Estado { get; set; }

        [ForeignKey(nameof(prfr_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbPreguntasFrecuentesprfr_UsuarioCreacionNavigation))]
        public virtual tbUsuarios prfr_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(prfr_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbPreguntasFrecuentesprfr_UsuarioModificacionNavigation))]
        public virtual tbUsuarios prfr_UsuarioModificacionNavigation { get; set; }
    }
}