// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbPreguntasPorCuestionario
    {
        public tbPreguntasPorCuestionario()
        {
            tbOpcionesPorPregunta = new HashSet<tbOpcionesPorPregunta>();
        }

        public int prcu_Id { get; set; }
        public int cues_Id { get; set; }
        public bool prcu_EsRespuestaBreve { get; set; }
        public string prcu_Pregunta { get; set; }
        public decimal? prcu_Puntuacion { get; set; }

        public virtual tbCuestionarios cues { get; set; }
        public virtual ICollection<tbOpcionesPorPregunta> tbOpcionesPorPregunta { get; set; }
    }
}