// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbPreguntasPorCuestionario", Schema = "Gest")]
    public partial class tbPreguntasPorCuestionario
    {
        public tbPreguntasPorCuestionario()
        {
            tbOpcionesPorPregunta = new HashSet<tbOpcionesPorPregunta>();
        }

        [Key]
        public int prcu_Id { get; set; }
        public int cues_Id { get; set; }
        public bool prcu_EsRespuestaBreve { get; set; }
        [Required]
        public string prcu_Pregunta { get; set; }
        [Column(TypeName = "decimal(2, 1)")]
        public decimal? prcu_Puntuacion { get; set; }

        [ForeignKey(nameof(cues_Id))]
        [InverseProperty(nameof(tbCuestionarios.tbPreguntasPorCuestionario))]
        public virtual tbCuestionarios cues { get; set; }
        [InverseProperty("prcu")]
        public virtual ICollection<tbOpcionesPorPregunta> tbOpcionesPorPregunta { get; set; }
    }
}