// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbPuestos
    {
        public TbPuestos()
        {
            TbEmpleados = new HashSet<TbEmpleados>();
        }

        public int PustId { get; set; }
        public string PustDescripcionPuesto { get; set; }
        public int? PustUsuarioCreacion { get; set; }
        public DateTime? PustFechaCreacion { get; set; }
        public int? PustUsuarioModificacion { get; set; }
        public DateTime? PustFechaModificacion { get; set; }
        public bool? PustEstado { get; set; }

        public virtual TbUsuarios PustUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios PustUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleados { get; set; }
    }
}