// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbPuestos", Schema = "Gral")]
    [Index(nameof(pust_DescripcionPuesto), Name = "UQ__tbPuesto__927C9349E17D565A", IsUnique = true)]
    public partial class tbPuestos
    {
        public tbPuestos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        [Key]
        public int pust_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string pust_DescripcionPuesto { get; set; }
        public int? pust_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pust_FechaCreacion { get; set; }
        public int? pust_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? pust_FechaModificacion { get; set; }
        public bool? pust_Estado { get; set; }

        [ForeignKey(nameof(pust_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbPuestospust_UsuarioCreacionNavigation))]
        public virtual tbUsuarios pust_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(pust_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbPuestospust_UsuarioModificacionNavigation))]
        public virtual tbUsuarios pust_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("pust")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}