// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbPuestos
    {
        public tbPuestos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int pust_Id { get; set; }
        public string pust_DescripcionPuesto { get; set; }
        public int? pust_UsuarioCreacion { get; set; }
        public DateTime? pust_FechaCreacion { get; set; }
        public int? pust_UsuarioModificacion { get; set; }
        public DateTime? pust_FechaModificacion { get; set; }
        public bool? pust_Estado { get; set; }

        public virtual tbUsuarios pust_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios pust_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}