// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRegionales
    {
        public tbRegionales()
        {
            tbFacultadPorRegional = new HashSet<tbFacultadPorRegional>();
        }

        public int regi_Id { get; set; }
        public int univ_Id { get; set; }
        public string muni_Id { get; set; }
        public string regi_DescripcionRegional { get; set; }
        public string regi_Abreviatura { get; set; }
        public int? regi_UsuarioCreacion { get; set; }
        public DateTime? regi_FechaCreacion { get; set; }
        public int? regi_UsuarioModificacion { get; set; }
        public DateTime? regi_FechaModificacion { get; set; }
        public bool? regi_Estado { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios regi_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios regi_UsuarioModificacionNavigation { get; set; }
        public virtual tbUniversidades univ { get; set; }
        public virtual ICollection<tbFacultadPorRegional> tbFacultadPorRegional { get; set; }
    }
}