// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRecibos", Schema = "Gest")]
    public partial class tbRecibos
    {
        [Key]
        public int reci_Id { get; set; }
        public int empl_Id { get; set; }
        [Required]
        [StringLength(255)]
        public string reci_Para { get; set; }
        [Column(TypeName = "date")]
        public DateTime reci_PeriodoInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? reci_PeriodoFinal { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime reci_FechaHoraLimite { get; set; }
        public string reci_Certificacion { get; set; }
        public int? reci_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? reci_FechaCreacion { get; set; }
        public int? reci_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? reci_FechaModificacion { get; set; }
        public bool? reci_Estado { get; set; }

        [ForeignKey(nameof(empl_Id))]
        [InverseProperty(nameof(tbEmpleados.tbRecibos))]
        public virtual tbEmpleados empl { get; set; }
        [ForeignKey(nameof(reci_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbRecibosreci_UsuarioCreacionNavigation))]
        public virtual tbUsuarios reci_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(reci_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbRecibosreci_UsuarioModificacionNavigation))]
        public virtual tbUsuarios reci_UsuarioModificacionNavigation { get; set; }
    }
}