// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRegionales
    {
        public TbRegionales()
        {
            TbFacultadPorRegional = new HashSet<TbFacultadPorRegional>();
        }

        public int RegiId { get; set; }
        public int UnivId { get; set; }
        public string MuniId { get; set; }
        public string RegiDescripcionRegional { get; set; }
        public string RegiAbreviatura { get; set; }
        public int? RegiUsuarioCreacion { get; set; }
        public DateTime? RegiFechaCreacion { get; set; }
        public int? RegiUsuarioModificacion { get; set; }
        public DateTime? RegiFechaModificacion { get; set; }
        public bool? RegiEstado { get; set; }

        public virtual TbMunicipios Muni { get; set; }
        public virtual TbUsuarios RegiUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios RegiUsuarioModificacionNavigation { get; set; }
        public virtual TbUniversidades Univ { get; set; }
        public virtual ICollection<TbFacultadPorRegional> TbFacultadPorRegional { get; set; }
    }
}