// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRegionalCorporativa", Schema = "Gral")]
    [Index(nameof(reco_NombreRegionalCorportiva), Name = "UQ_tbRegionalCorporativa_reco_NombreRegionalCorportiva", IsUnique = true)]
    public partial class tbRegionalCorporativa
    {
        public tbRegionalCorporativa()
        {
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
        }

        [Key]
        public int reco_Id { get; set; }
        [Required]
        [StringLength(4)]
        public string muni_Id { get; set; }
        [Required]
        [StringLength(150)]
        public string reco_NombreRegionalCorportiva { get; set; }
        [Required]
        [StringLength(200)]
        public string reco_DireccionExacta { get; set; }
        public int? reco_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? reco_FechaCreacion { get; set; }
        public int? reco_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? reco_FechaModificacion { get; set; }
        public bool? reco_Estado { get; set; }

        [ForeignKey(nameof(muni_Id))]
        [InverseProperty(nameof(tbMunicipios.tbRegionalCorporativa))]
        public virtual tbMunicipios muni { get; set; }
        [ForeignKey(nameof(reco_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbRegionalCorporativareco_UsuarioCreacionNavigation))]
        public virtual tbUsuarios reco_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(reco_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbRegionalCorporativareco_UsuarioModificacionNavigation))]
        public virtual tbUsuarios reco_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("reco")]
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
    }
}