// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRecibos
    {
        public int reci_Id { get; set; }
        public int empl_Id { get; set; }
        public string reci_Para { get; set; }
        public DateTime reci_PeriodoInicio { get; set; }
        public DateTime? reci_PeriodoFinal { get; set; }
        public DateTime reci_FechaHoraLimite { get; set; }
        public string reci_Certificacion { get; set; }
        public int? reci_UsuarioCreacion { get; set; }
        public DateTime? reci_FechaCreacion { get; set; }
        public int? reci_UsuarioModificacion { get; set; }
        public DateTime? reci_FechaModificacion { get; set; }
        public bool? reci_Estado { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios reci_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios reci_UsuarioModificacionNavigation { get; set; }
    }
}