// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRecibosPorOptante
    {
        public int reop_Id { get; set; }
        public int opta_Id { get; set; }
        public string reop_Descripcion { get; set; }
        public decimal reop_HorasTotalesRealizadas { get; set; }
        public decimal? reop_PrecioUnitario { get; set; }
        public decimal reop_Total { get; set; }

        public virtual tbOptantes opta { get; set; }
    }
}