// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRegionalCorporativa
    {
        public TbRegionalCorporativa()
        {
            TbComponentesPorRegionalPorEmpleado = new HashSet<TbComponentesPorRegionalPorEmpleado>();
        }

        public int RecoId { get; set; }
        public string MuniId { get; set; }
        public string RecoNombreRegionalCorportiva { get; set; }
        public string RecoDireccionExacta { get; set; }
        public int? RecoUsuarioCreacion { get; set; }
        public DateTime? RecoFechaCreacion { get; set; }
        public int? RecoUsuarioModificacion { get; set; }
        public DateTime? RecoFechaModificacion { get; set; }
        public bool? RecoEstado { get; set; }

        public virtual TbMunicipios Muni { get; set; }
        public virtual TbUsuarios RecoUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios RecoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbComponentesPorRegionalPorEmpleado> TbComponentesPorRegionalPorEmpleado { get; set; }
    }
}