// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRegionalCorporativa
    {
        public tbRegionalCorporativa()
        {
            tbComponentesPorRegionalPorEmpleado = new HashSet<tbComponentesPorRegionalPorEmpleado>();
        }

        public int reco_Id { get; set; }
        public string muni_Id { get; set; }
        public string reco_NombreRegionalCorportiva { get; set; }
        public string reco_DireccionExacta { get; set; }
        public int? reco_UsuarioCreacion { get; set; }
        public DateTime? reco_FechaCreacion { get; set; }
        public int? reco_UsuarioModificacion { get; set; }
        public DateTime? reco_FechaModificacion { get; set; }
        public bool? reco_Estado { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios reco_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios reco_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComponentesPorRegionalPorEmpleado> tbComponentesPorRegionalPorEmpleado { get; set; }
    }
}