// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRecibos
    {
        public int ReciId { get; set; }
        public int EmplId { get; set; }
        public string ReciPara { get; set; }
        public DateTime ReciPeriodoInicio { get; set; }
        public DateTime? ReciPeriodoFinal { get; set; }
        public DateTime ReciFechaHoraLimite { get; set; }
        public string ReciCertificacion { get; set; }
        public int? ReciUsuarioCreacion { get; set; }
        public DateTime? ReciFechaCreacion { get; set; }
        public int? ReciUsuarioModificacion { get; set; }
        public DateTime? ReciFechaModificacion { get; set; }
        public bool? ReciEstado { get; set; }

        public virtual TbEmpleados Empl { get; set; }
        public virtual TbUsuarios ReciUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios ReciUsuarioModificacionNavigation { get; set; }
    }
}