// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRespuestasPorOptante
    {
        public int CupaId { get; set; }
        public int OpprId { get; set; }
        public int OptaId { get; set; }
        public string CupaRespuesta { get; set; }
        public DateTime CupaFechaRealizado { get; set; }

        public virtual TbOpcionesPorPregunta Oppr { get; set; }
        public virtual TbOptantes Opta { get; set; }
    }
}