// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRespuestasPorOptante", Schema = "Gest")]
    public partial class tbRespuestasPorOptante
    {
        [Key]
        public int cupa_Id { get; set; }
        public int oppr_Id { get; set; }
        public int opta_Id { get; set; }
        public string cupa_respuesta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime cupa_FechaRealizado { get; set; }

        [ForeignKey(nameof(oppr_Id))]
        [InverseProperty(nameof(tbOpcionesPorPregunta.tbRespuestasPorOptante))]
        public virtual tbOpcionesPorPregunta oppr { get; set; }
        [ForeignKey(nameof(opta_Id))]
        [InverseProperty(nameof(tbOptantes.tbRespuestasPorOptante))]
        public virtual tbOptantes opta { get; set; }
    }
}