// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRecibosPorOptante
    {
        public int ReopId { get; set; }
        public int OptaId { get; set; }
        public string ReopDescripcion { get; set; }
        public decimal ReopHorasTotalesRealizadas { get; set; }
        public decimal? ReopPrecioUnitario { get; set; }
        public decimal ReopTotal { get; set; }

        public virtual TbOptantes Opta { get; set; }
    }
}