// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRegionales", Schema = "Gral")]
    [Index(nameof(regi_Abreviatura), Name = "UQ__tbRegion__B4C8C711BB9CBBE6", IsUnique = true)]
    [Index(nameof(regi_DescripcionRegional), Name = "UQ__tbRegion__EE1F886844309BA4", IsUnique = true)]
    public partial class tbRegionales
    {
        public tbRegionales()
        {
            tbFacultadPorRegional = new HashSet<tbFacultadPorRegional>();
        }

        [Key]
        public int regi_Id { get; set; }
        public int univ_Id { get; set; }
        [Required]
        [StringLength(4)]
        public string muni_Id { get; set; }
        [Required]
        [StringLength(60)]
        public string regi_DescripcionRegional { get; set; }
        [StringLength(5)]
        public string regi_Abreviatura { get; set; }
        public int? regi_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? regi_FechaCreacion { get; set; }
        public int? regi_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? regi_FechaModificacion { get; set; }
        public bool? regi_Estado { get; set; }

        [ForeignKey(nameof(muni_Id))]
        [InverseProperty(nameof(tbMunicipios.tbRegionales))]
        public virtual tbMunicipios muni { get; set; }
        [ForeignKey(nameof(regi_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbRegionalesregi_UsuarioCreacionNavigation))]
        public virtual tbUsuarios regi_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(regi_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbRegionalesregi_UsuarioModificacionNavigation))]
        public virtual tbUsuarios regi_UsuarioModificacionNavigation { get; set; }
        [ForeignKey(nameof(univ_Id))]
        [InverseProperty(nameof(tbUniversidades.tbRegionales))]
        public virtual tbUniversidades univ { get; set; }
        [InverseProperty("regi")]
        public virtual ICollection<tbFacultadPorRegional> tbFacultadPorRegional { get; set; }
    }
}