// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRespuestasPorOptante
    {
        public int cupa_Id { get; set; }
        public int oppr_Id { get; set; }
        public int opta_Id { get; set; }
        public string cupa_respuesta { get; set; }
        public DateTime cupa_FechaRealizado { get; set; }

        public virtual tbOpcionesPorPregunta oppr { get; set; }
        public virtual tbOptantes opta { get; set; }
    }
}