// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRecibosPorOptante", Schema = "Gest")]
    public partial class tbRecibosPorOptante
    {
        [Key]
        public int reop_Id { get; set; }
        public int opta_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string reop_Descripcion { get; set; }
        [Column(TypeName = "decimal(2, 1)")]
        public decimal reop_HorasTotalesRealizadas { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? reop_PrecioUnitario { get; set; }
        [Column(TypeName = "decimal(6, 2)")]
        public decimal reop_Total { get; set; }

        [ForeignKey(nameof(opta_Id))]
        [InverseProperty(nameof(tbOptantes.tbRecibosPorOptante))]
        public virtual tbOptantes opta { get; set; }
    }
}