// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbRoles", Schema = "Accs")]
    [Index(nameof(role_DescripcionRol), Name = "UQ__tbRoles__AC38D9C21860C3A8", IsUnique = true)]
    [Index(nameof(role_DescripcionRol), Name = "UQ_tbRoles_role_DescripcionRol", IsUnique = true)]
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbModulosPorRoles = new HashSet<tbModulosPorRoles>();
        }

        [Key]
        public int role_Id { get; set; }
        [Required]
        [StringLength(100)]
        public string role_DescripcionRol { get; set; }
        public int? role_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? role_FechaCreacion { get; set; }
        public int? role_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? role_FechaModificacion { get; set; }
        public bool? role_Estado { get; set; }

        [ForeignKey(nameof(role_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbRolesrole_UsuarioCreacionNavigation))]
        public virtual tbUsuarios role_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(role_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbRolesrole_UsuarioModificacionNavigation))]
        public virtual tbUsuarios role_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("role")]
        public virtual ICollection<tbModulosPorRoles> tbModulosPorRoles { get; set; }
    }
}