// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbModulosPorRoles = new HashSet<tbModulosPorRoles>();
        }

        public string codigo { get; set; }
        public int role_Id { get; set; }
        public string role_DescripcionRol { get; set; }
        public int? role_UsuarioCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public DateTime? role_FechaCreacion { get; set; }
        public int? role_UsuarioModificacion { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? role_FechaModificacion { get; set; }
        public bool? role_Estado { get; set; }

        public virtual tbUsuarios role_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios role_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbModulosPorRoles> tbModulosPorRoles { get; set; }
    }
}