// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbRoles
    {
        public TbRoles()
        {
            TbModulosPorRoles = new HashSet<TbModulosPorRoles>();
        }

        public int RoleId { get; set; }
        public string RoleDescripcionRol { get; set; }
        public int? RoleUsuarioCreacion { get; set; }
        public DateTime? RoleFechaCreacion { get; set; }
        public int? RoleUsuarioModificacion { get; set; }
        public DateTime? RoleFechaModificacion { get; set; }
        public bool? RoleEstado { get; set; }

        public virtual TbUsuarios RoleUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios RoleUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbModulosPorRoles> TbModulosPorRoles { get; set; }
    }
}