// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbTipoSangre
    {
        public TbTipoSangre()
        {
            TbEmpleados = new HashSet<TbEmpleados>();
            TbOptantes = new HashSet<TbOptantes>();
        }

        public int TisaId { get; set; }
        public string TisaDescripcion { get; set; }
        public int? TisaUsuarioCreacion { get; set; }
        public DateTime? TisaFechaCreacion { get; set; }
        public int? TisaUsuarioModificacion { get; set; }
        public DateTime? TisaFechamodificacion { get; set; }
        public bool? TisaEstado { get; set; }

        public virtual TbUsuarios TisaUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios TisaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleados { get; set; }
        public virtual ICollection<TbOptantes> TbOptantes { get; set; }
    }
}