// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbTipoDocumento
    {
        public TbTipoDocumento()
        {
            TbDocumentos = new HashSet<TbDocumentos>();
            TbDocumentosOptantes = new HashSet<TbDocumentosOptantes>();
        }

        public int TidoId { get; set; }
        public string TidoDescripcion { get; set; }
        public int? TidoUsuarioCreacion { get; set; }
        public DateTime? TidoFechaCreacion { get; set; }
        public int? TidoUsuarioModificacion { get; set; }
        public DateTime? TidoFechaModificacion { get; set; }
        public bool? TidoEstado { get; set; }

        public virtual TbUsuarios TidoUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios TidoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDocumentos> TbDocumentos { get; set; }
        public virtual ICollection<TbDocumentosOptantes> TbDocumentosOptantes { get; set; }
    }
}