// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbTipoDocumento
    {
        public tbTipoDocumento()
        {
            tbDocumentos = new HashSet<tbDocumentos>();
        }

        public int tido_Id { get; set; }
        public string tido_Descripcion { get; set; }
        public int? tido_UsuarioCreacion { get; set; }
        public DateTime? tido_FechaCreacion { get; set; }
        public int? tido_UsuarioModificacion { get; set; }
        public DateTime? tido_FechaModificacion { get; set; }
        public bool? tido_Estado { get; set; }

        public virtual tbUsuarios tido_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios tido_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
    }
}