// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbTipoSangre
    {
        public tbTipoSangre()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbOptantes = new HashSet<tbOptantes>();
        }

        public int tisa_Id { get; set; }
        public string tisa_Descripcion { get; set; }
        public int? tisa_UsuarioCreacion { get; set; }
        public DateTime? tisa_FechaCreacion { get; set; }
        public int? tisa_UsuarioModificacion { get; set; }
        public DateTime? tisa_Fechamodificacion { get; set; }
        public bool? tisa_Estado { get; set; }

        public virtual tbUsuarios tisa_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios tisa_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbOptantes> tbOptantes { get; set; }
    }
}