// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbTipoDocumento", Schema = "Gral")]
    [Index(nameof(tido_Descripcion), Name = "UQ__tbTipoDo__10806C995A6DB941", IsUnique = true)]
    public partial class tbTipoDocumento
    {
        public tbTipoDocumento()
        {
            tbDocumentos = new HashSet<tbDocumentos>();
            tbDocumentosOptantes = new HashSet<tbDocumentosOptantes>();
        }

        [Key]
        public int tido_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string tido_Descripcion { get; set; }
        public int? tido_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tido_FechaCreacion { get; set; }
        public int? tido_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? tido_FechaModificacion { get; set; }
        public bool? tido_Estado { get; set; }

        [ForeignKey(nameof(tido_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.tbTipoDocumentotido_UsuarioCreacionNavigation))]
        public virtual tbUsuarios tido_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(tido_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.tbTipoDocumentotido_UsuarioModificacionNavigation))]
        public virtual tbUsuarios tido_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("tido")]
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
        [InverseProperty("tido")]
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantes { get; set; }
    }
}