// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbTokens
    {
        public int ToknId { get; set; }
        public int UsuaId { get; set; }
        public string ToknJsonToken { get; set; }
        public bool? ToknSesionWeb { get; set; }

        public virtual TbUsuarios Usua { get; set; }
    }
}