// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbTokens", Schema = "Comn")]
    public partial class tbTokens
    {
        [Key]
        public int tokn_Id { get; set; }
        public int usua_Id { get; set; }
        [Required]
        public string tokn_JsonToken { get; set; }
        public bool? tokn_SesionWeb { get; set; }

        [ForeignKey(nameof(usua_Id))]
        [InverseProperty(nameof(tbUsuarios.tbTokens))]
        public virtual tbUsuarios usua { get; set; }
    }
}