// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbUniversidades
    {
        public TbUniversidades()
        {
            TbRegionales = new HashSet<TbRegionales>();
        }

        public int UnivId { get; set; }
        public string UnivDescripcionUniversidad { get; set; }
        public string UnivAbreviatura { get; set; }
        public int? UnivUsuarioCreacion { get; set; }
        public DateTime? UnivFechaCreacion { get; set; }
        public int? UnivUsuarioModificacion { get; set; }
        public DateTime? UnivFechaModificacion { get; set; }
        public bool? UnivEstado { get; set; }

        public virtual TbUsuarios UnivUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios UnivUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbRegionales> TbRegionales { get; set; }
    }
}