// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbActividadesPorOptanteacpe_UsuarioCreacionNavigation = new HashSet<tbActividadesPorOptante>();
            tbActividadesPorOptanteacpe_UsuarioModificacionNavigation = new HashSet<tbActividadesPorOptante>();
            tbActividadesacti_UsuarioCreacionNavigation = new HashSet<tbActividades>();
            tbActividadesacti_UsuarioModificacionNavigation = new HashSet<tbActividades>();
            tbBancosbanc_UsuarioCreacionNavigation = new HashSet<tbBancos>();
            tbBancosbanc_UsuarioModificacionNavigation = new HashSet<tbBancos>();
            tbBeneficiosbene_UsuarioCreacionNavigation = new HashSet<tbBeneficios>();
            tbBeneficiosbene_UsuarioModificacionNavigation = new HashSet<tbBeneficios>();
            tbCarrerascarr_UsuarioCreacionNavigation = new HashSet<tbCarreras>();
            tbCarrerascarr_UsuarioModificacionNavigation = new HashSet<tbCarreras>();
            tbComponentescomp_UsuarioCreacionNavigation = new HashSet<tbComponentes>();
            tbComponentescomp_UsuarioModificacionNavigation = new HashSet<tbComponentes>();
            tbCuestionarioscues_UsuarioCreacionNavigation = new HashSet<tbCuestionarios>();
            tbCuestionarioscues_UsuarioModificacionNavigation = new HashSet<tbCuestionarios>();
            tbDepartamentosdepa_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbDiscusionesdisc_UsuarioCreacionNavigation = new HashSet<tbDiscusiones>();
            tbDiscusionesdisc_UsuarioModificacionNavigation = new HashSet<tbDiscusiones>();
            tbDocumentosOptantesdoop_UsuarioCreacionNavigation = new HashSet<tbDocumentosOptantes>();
            tbDocumentosOptantesdoop_UsuarioModificacionNavigation = new HashSet<tbDocumentosOptantes>();
            tbDocumentosdocu_UsuarioCreacionNavigation = new HashSet<tbDocumentos>();
            tbDocumentosdocu_UsuarioModificacionNavigation = new HashSet<tbDocumentos>();
            tbEmpleadosempl_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEmpresasempr_UsuarioCreacionNavigation = new HashSet<tbEmpresas>();
            tbEmpresasempr_UsuarioModificacionNavigation = new HashSet<tbEmpresas>();
            tbEstadosCivilescivi_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilescivi_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacultadesfacu_UsuarioCreacionNavigation = new HashSet<tbFacultades>();
            tbFacultadesfacu_UsuarioModificacionNavigation = new HashSet<tbFacultades>();
            tbForosPorActividadfoac_UsuarioCreacionNavigation = new HashSet<tbForosPorActividad>();
            tbForosPorActividadfoac_UsuarioModificacionNavigation = new HashSet<tbForosPorActividad>();
            tbForosPorEmpleadosfoem_UsuarioCreacionNavigation = new HashSet<tbForosPorEmpleados>();
            tbForosPorEmpleadosfoem_UsuarioModificacionNavigation = new HashSet<tbForosPorEmpleados>();
            tbForosforo_UsuarioCreacionNavigation = new HashSet<tbForos>();
            tbForosforo_UsuarioModificacionNavigation = new HashSet<tbForos>();
            tbHojaTiempoPorOptantehoto_UsuarioCreacionNavigation = new HashSet<tbHojaTiempoPorOptante>();
            tbHojaTiempoPorOptantehoto_UsuarioModificacionNavigation = new HashSet<tbHojaTiempoPorOptante>();
            tbHojaTiempohoti_UsuarioCreacionNavigation = new HashSet<tbHojaTiempo>();
            tbHojaTiempohoti_UsuarioModificacionNavigation = new HashSet<tbHojaTiempo>();
            tbModulosmodu_UsuarioCreacionNavigation = new HashSet<tbModulos>();
            tbModulosmodu_UsuarioModificacionNavigation = new HashSet<tbModulos>();
            tbMunicipiosmuni_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbNotificacionesPorUsuarionapu_UsuarioCreacionNavigation = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesPorUsuarionapu_UsuarioModificacionNavigation = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesPorUsuariousua = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesnoti_UsuarioCreacionNavigation = new HashSet<tbNotificaciones>();
            tbNotificacionesnoti_UsuarioModificacionNavigation = new HashSet<tbNotificaciones>();
            tbOptantesopta_UsuarioCreacionNavigation = new HashSet<tbOptantes>();
            tbOptantesopta_UsuarioModificacionNavigation = new HashSet<tbOptantes>();
            tbPreguntasFrecuentesprfr_UsuarioCreacionNavigation = new HashSet<tbPreguntasFrecuentes>();
            tbPreguntasFrecuentesprfr_UsuarioModificacionNavigation = new HashSet<tbPreguntasFrecuentes>();
            tbProyectospryt_UsuarioCreacionNavigation = new HashSet<tbProyectos>();
            tbProyectospryt_UsuarioModificacionNavigation = new HashSet<tbProyectos>();
            tbPuestospust_UsuarioCreacionNavigation = new HashSet<tbPuestos>();
            tbPuestospust_UsuarioModificacionNavigation = new HashSet<tbPuestos>();
            tbRecibosreci_UsuarioCreacionNavigation = new HashSet<tbRecibos>();
            tbRecibosreci_UsuarioModificacionNavigation = new HashSet<tbRecibos>();
            tbRegionalCorporativareco_UsuarioCreacionNavigation = new HashSet<tbRegionalCorporativa>();
            tbRegionalCorporativareco_UsuarioModificacionNavigation = new HashSet<tbRegionalCorporativa>();
            tbRegionalesregi_UsuarioCreacionNavigation = new HashSet<tbRegionales>();
            tbRegionalesregi_UsuarioModificacionNavigation = new HashSet<tbRegionales>();
            tbRolesrole_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbTipoDocumentotido_UsuarioCreacionNavigation = new HashSet<tbTipoDocumento>();
            tbTipoDocumentotido_UsuarioModificacionNavigation = new HashSet<tbTipoDocumento>();
            tbTipoSangretisa_UsuarioCreacionNavigation = new HashSet<tbTipoSangre>();
            tbTipoSangretisa_UsuarioModificacionNavigation = new HashSet<tbTipoSangre>();
            tbTokens = new HashSet<tbTokens>();
            tbUniversidadesuniv_UsuarioCreacionNavigation = new HashSet<tbUniversidades>();
            tbUniversidadesuniv_UsuarioModificacionNavigation = new HashSet<tbUniversidades>();
        }

        public int usua_Id { get; set; }
        public int emop_Id { get; set; }
        public int role_Id { get; set; }
        public bool usua_Administrador { get; set; }
        public bool usua_EsOptante { get; set; }
        public string usua_Usuario { get; set; }
        public string usua_Contraseña { get; set; }
        public int? usua_UsuarioCreacion { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptanteacpe_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptanteacpe_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividadesacti_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividadesacti_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbBancos> tbBancosbanc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbBancos> tbBancosbanc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbBeneficios> tbBeneficiosbene_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbBeneficios> tbBeneficiosbene_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCarreras> tbCarrerascarr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCarreras> tbCarrerascarr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComponentes> tbComponentescomp_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbComponentes> tbComponentescomp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCuestionarios> tbCuestionarioscues_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCuestionarios> tbCuestionarioscues_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDiscusiones> tbDiscusionesdisc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDiscusiones> tbDiscusionesdisc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantesdoop_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantesdoop_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentosdocu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentosdocu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasempr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasempr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilescivi_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilescivi_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacultades> tbFacultadesfacu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbFacultades> tbFacultadesfacu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbForosPorActividad> tbForosPorActividadfoac_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbForosPorActividad> tbForosPorActividadfoac_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleadosfoem_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleadosfoem_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbForos> tbForosforo_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbForos> tbForosforo_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbHojaTiempoPorOptante> tbHojaTiempoPorOptantehoto_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbHojaTiempoPorOptante> tbHojaTiempoPorOptantehoto_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbHojaTiempo> tbHojaTiempohoti_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbHojaTiempo> tbHojaTiempohoti_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbModulos> tbModulosmodu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbModulos> tbModulosmodu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuarionapu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuarionapu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuariousua { get; set; }
        public virtual ICollection<tbNotificaciones> tbNotificacionesnoti_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbNotificaciones> tbNotificacionesnoti_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbOptantes> tbOptantesopta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbOptantes> tbOptantesopta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPreguntasFrecuentes> tbPreguntasFrecuentesprfr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPreguntasFrecuentes> tbPreguntasFrecuentesprfr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProyectos> tbProyectospryt_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProyectos> tbProyectospryt_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPuestos> tbPuestospust_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPuestos> tbPuestospust_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRecibos> tbRecibosreci_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRecibos> tbRecibosreci_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativareco_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativareco_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRegionales> tbRegionalesregi_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRegionales> tbRegionalesregi_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTipoDocumento> tbTipoDocumentotido_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTipoDocumento> tbTipoDocumentotido_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTipoSangre> tbTipoSangretisa_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTipoSangre> tbTipoSangretisa_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTokens> tbTokens { get; set; }
        public virtual ICollection<tbUniversidades> tbUniversidadesuniv_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUniversidades> tbUniversidadesuniv_UsuarioModificacionNavigation { get; set; }
    }
}