// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    public partial class TbUsuarios
    {
        public TbUsuarios()
        {
            InverseUsuaUsuarioCreacionNavigation = new HashSet<TbUsuarios>();
            InverseUsuaUsuarioModificacionNavigation = new HashSet<TbUsuarios>();
            TbActividadesActiUsuarioCreacionNavigation = new HashSet<TbActividades>();
            TbActividadesActiUsuarioModificacionNavigation = new HashSet<TbActividades>();
            TbActividadesPorOptanteAcpeUsuarioCreacionNavigation = new HashSet<TbActividadesPorOptante>();
            TbActividadesPorOptanteAcpeUsuarioModificacionNavigation = new HashSet<TbActividadesPorOptante>();
            TbBancosBancUsuarioCreacionNavigation = new HashSet<TbBancos>();
            TbBancosBancUsuarioModificacionNavigation = new HashSet<TbBancos>();
            TbBeneficiosBeneUsuarioCreacionNavigation = new HashSet<TbBeneficios>();
            TbBeneficiosBeneUsuarioModificacionNavigation = new HashSet<TbBeneficios>();
            TbCarrerasCarrUsuarioCreacionNavigation = new HashSet<TbCarreras>();
            TbCarrerasCarrUsuarioModificacionNavigation = new HashSet<TbCarreras>();
            TbComponentesCompUsuarioCreacionNavigation = new HashSet<TbComponentes>();
            TbComponentesCompUsuarioModificacionNavigation = new HashSet<TbComponentes>();
            TbCuestionariosCuesUsuarioCreacionNavigation = new HashSet<TbCuestionarios>();
            TbCuestionariosCuesUsuarioModificacionNavigation = new HashSet<TbCuestionarios>();
            TbDepartamentosDepaUsuarioCreacionNavigation = new HashSet<TbDepartamentos>();
            TbDepartamentosDepaUsuarioModificacionNavigation = new HashSet<TbDepartamentos>();
            TbDiscusionesDiscUsuarioCreacionNavigation = new HashSet<TbDiscusiones>();
            TbDiscusionesDiscUsuarioModificacionNavigation = new HashSet<TbDiscusiones>();
            TbDocumentosDocuUsuarioCreacionNavigation = new HashSet<TbDocumentos>();
            TbDocumentosDocuUsuarioModificacionNavigation = new HashSet<TbDocumentos>();
            TbDocumentosOptantesDoopUsuarioCreacionNavigation = new HashSet<TbDocumentosOptantes>();
            TbDocumentosOptantesDoopUsuarioModificacionNavigation = new HashSet<TbDocumentosOptantes>();
            TbEmpleadosEmplUsuarioCreacionNavigation = new HashSet<TbEmpleados>();
            TbEmpleadosEmplUsuarioModificacionNavigation = new HashSet<TbEmpleados>();
            TbEmpresasEmprUsuarioCreacionNavigation = new HashSet<TbEmpresas>();
            TbEmpresasEmprUsuarioModificacionNavigation = new HashSet<TbEmpresas>();
            TbEstadosCivilesCiviUsuarioCreacionNavigation = new HashSet<TbEstadosCiviles>();
            TbEstadosCivilesCiviUsuarioModificacionNavigation = new HashSet<TbEstadosCiviles>();
            TbFacultadesFacuUsuarioCreacionNavigation = new HashSet<TbFacultades>();
            TbFacultadesFacuUsuarioModificacionNavigation = new HashSet<TbFacultades>();
            TbForosForoUsuarioCreacionNavigation = new HashSet<TbForos>();
            TbForosForoUsuarioModificacionNavigation = new HashSet<TbForos>();
            TbForosPorActividadFoacUsuarioCreacionNavigation = new HashSet<TbForosPorActividad>();
            TbForosPorActividadFoacUsuarioModificacionNavigation = new HashSet<TbForosPorActividad>();
            TbForosPorEmpleadosFoemUsuarioCreacionNavigation = new HashSet<TbForosPorEmpleados>();
            TbForosPorEmpleadosFoemUsuarioModificacionNavigation = new HashSet<TbForosPorEmpleados>();
            TbHojaTiempoHotiUsuarioCreacionNavigation = new HashSet<TbHojaTiempo>();
            TbHojaTiempoHotiUsuarioModificacionNavigation = new HashSet<TbHojaTiempo>();
            TbHojaTiempoPorOptanteHotoUsuarioCreacionNavigation = new HashSet<TbHojaTiempoPorOptante>();
            TbHojaTiempoPorOptanteHotoUsuarioModificacionNavigation = new HashSet<TbHojaTiempoPorOptante>();
            TbModulosModuUsuarioCreacionNavigation = new HashSet<TbModulos>();
            TbModulosModuUsuarioModificacionNavigation = new HashSet<TbModulos>();
            TbMunicipiosMuniUsuarioCreacionNavigation = new HashSet<TbMunicipios>();
            TbMunicipiosMuniUsuarioModificacionNavigation = new HashSet<TbMunicipios>();
            TbNotificacionesNotiUsuarioCreacionNavigation = new HashSet<TbNotificaciones>();
            TbNotificacionesNotiUsuarioModificacionNavigation = new HashSet<TbNotificaciones>();
            TbNotificacionesPorUsuarioNapuUsuarioCreacionNavigation = new HashSet<TbNotificacionesPorUsuario>();
            TbNotificacionesPorUsuarioNapuUsuarioModificacionNavigation = new HashSet<TbNotificacionesPorUsuario>();
            TbNotificacionesPorUsuarioUsua = new HashSet<TbNotificacionesPorUsuario>();
            TbOptantesOptaUsuarioCreacionNavigation = new HashSet<TbOptantes>();
            TbOptantesOptaUsuarioModificacionNavigation = new HashSet<TbOptantes>();
            TbPreguntasFrecuentesPrfrUsuarioCreacionNavigation = new HashSet<TbPreguntasFrecuentes>();
            TbPreguntasFrecuentesPrfrUsuarioModificacionNavigation = new HashSet<TbPreguntasFrecuentes>();
            TbProyectosPrytUsuarioCreacionNavigation = new HashSet<TbProyectos>();
            TbProyectosPrytUsuarioModificacionNavigation = new HashSet<TbProyectos>();
            TbPuestosPustUsuarioCreacionNavigation = new HashSet<TbPuestos>();
            TbPuestosPustUsuarioModificacionNavigation = new HashSet<TbPuestos>();
            TbRecibosReciUsuarioCreacionNavigation = new HashSet<TbRecibos>();
            TbRecibosReciUsuarioModificacionNavigation = new HashSet<TbRecibos>();
            TbRegionalCorporativaRecoUsuarioCreacionNavigation = new HashSet<TbRegionalCorporativa>();
            TbRegionalCorporativaRecoUsuarioModificacionNavigation = new HashSet<TbRegionalCorporativa>();
            TbRegionalesRegiUsuarioCreacionNavigation = new HashSet<TbRegionales>();
            TbRegionalesRegiUsuarioModificacionNavigation = new HashSet<TbRegionales>();
            TbRolesRoleUsuarioCreacionNavigation = new HashSet<TbRoles>();
            TbRolesRoleUsuarioModificacionNavigation = new HashSet<TbRoles>();
            TbTipoDocumentoTidoUsuarioCreacionNavigation = new HashSet<TbTipoDocumento>();
            TbTipoDocumentoTidoUsuarioModificacionNavigation = new HashSet<TbTipoDocumento>();
            TbTipoSangreTisaUsuarioCreacionNavigation = new HashSet<TbTipoSangre>();
            TbTipoSangreTisaUsuarioModificacionNavigation = new HashSet<TbTipoSangre>();
            TbTokens = new HashSet<TbTokens>();
            TbUniversidadesUnivUsuarioCreacionNavigation = new HashSet<TbUniversidades>();
            TbUniversidadesUnivUsuarioModificacionNavigation = new HashSet<TbUniversidades>();
        }

        public int UsuaId { get; set; }
        public int EmopId { get; set; }
        public int RoleId { get; set; }
        public bool UsuaAdministrador { get; set; }
        public bool UsuaEsOptante { get; set; }
        public string UsuaUsuario { get; set; }
        public string UsuaContraseña { get; set; }
        public int? UsuaUsuarioCreacion { get; set; }
        public DateTime? UsuaFechaCreacion { get; set; }
        public int? UsuaUsuarioModificacion { get; set; }
        public DateTime? UsuaFechaModificacion { get; set; }
        public bool? UsuaEstado { get; set; }

        public virtual TbUsuarios UsuaUsuarioCreacionNavigation { get; set; }
        public virtual TbUsuarios UsuaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbUsuarios> InverseUsuaUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbUsuarios> InverseUsuaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbActividades> TbActividadesActiUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbActividades> TbActividadesActiUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbActividadesPorOptante> TbActividadesPorOptanteAcpeUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbActividadesPorOptante> TbActividadesPorOptanteAcpeUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbBancos> TbBancosBancUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbBancos> TbBancosBancUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbBeneficios> TbBeneficiosBeneUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbBeneficios> TbBeneficiosBeneUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbCarreras> TbCarrerasCarrUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbCarreras> TbCarrerasCarrUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbComponentes> TbComponentesCompUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbComponentes> TbComponentesCompUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbCuestionarios> TbCuestionariosCuesUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbCuestionarios> TbCuestionariosCuesUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDepartamentos> TbDepartamentosDepaUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbDepartamentos> TbDepartamentosDepaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDiscusiones> TbDiscusionesDiscUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbDiscusiones> TbDiscusionesDiscUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDocumentos> TbDocumentosDocuUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbDocumentos> TbDocumentosDocuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbDocumentosOptantes> TbDocumentosOptantesDoopUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbDocumentosOptantes> TbDocumentosOptantesDoopUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleadosEmplUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleadosEmplUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresasEmprUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresasEmprUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbEstadosCiviles> TbEstadosCivilesCiviUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbEstadosCiviles> TbEstadosCivilesCiviUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbFacultades> TbFacultadesFacuUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbFacultades> TbFacultadesFacuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbForos> TbForosForoUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbForos> TbForosForoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbForosPorActividad> TbForosPorActividadFoacUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbForosPorActividad> TbForosPorActividadFoacUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbForosPorEmpleados> TbForosPorEmpleadosFoemUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbForosPorEmpleados> TbForosPorEmpleadosFoemUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbHojaTiempo> TbHojaTiempoHotiUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbHojaTiempo> TbHojaTiempoHotiUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbHojaTiempoPorOptante> TbHojaTiempoPorOptanteHotoUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbHojaTiempoPorOptante> TbHojaTiempoPorOptanteHotoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbModulos> TbModulosModuUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbModulos> TbModulosModuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbMunicipios> TbMunicipiosMuniUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbMunicipios> TbMunicipiosMuniUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbNotificaciones> TbNotificacionesNotiUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbNotificaciones> TbNotificacionesNotiUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbNotificacionesPorUsuario> TbNotificacionesPorUsuarioNapuUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbNotificacionesPorUsuario> TbNotificacionesPorUsuarioNapuUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbNotificacionesPorUsuario> TbNotificacionesPorUsuarioUsua { get; set; }
        public virtual ICollection<TbOptantes> TbOptantesOptaUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbOptantes> TbOptantesOptaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbPreguntasFrecuentes> TbPreguntasFrecuentesPrfrUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbPreguntasFrecuentes> TbPreguntasFrecuentesPrfrUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbProyectos> TbProyectosPrytUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbProyectos> TbProyectosPrytUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbPuestos> TbPuestosPustUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbPuestos> TbPuestosPustUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbRecibos> TbRecibosReciUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbRecibos> TbRecibosReciUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbRegionalCorporativa> TbRegionalCorporativaRecoUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbRegionalCorporativa> TbRegionalCorporativaRecoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbRegionales> TbRegionalesRegiUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbRegionales> TbRegionalesRegiUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbRoles> TbRolesRoleUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbRoles> TbRolesRoleUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbTipoDocumento> TbTipoDocumentoTidoUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbTipoDocumento> TbTipoDocumentoTidoUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbTipoSangre> TbTipoSangreTisaUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbTipoSangre> TbTipoSangreTisaUsuarioModificacionNavigation { get; set; }
        public virtual ICollection<TbTokens> TbTokens { get; set; }
        public virtual ICollection<TbUniversidades> TbUniversidadesUnivUsuarioCreacionNavigation { get; set; }
        public virtual ICollection<TbUniversidades> TbUniversidadesUnivUsuarioModificacionNavigation { get; set; }
    }
}