// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace USAID_Pasantes.Entities.Entities
{
    [Table("tbUsuarios", Schema = "Accs")]
    [Index(nameof(usua_Usuario), Name = "UQ__tbUsuari__9ED44AB45D2A9E8B", IsUnique = true)]
    [Index(nameof(usua_Usuario), Name = "UQ_usua_Usuario", IsUnique = true)]
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbActividadesPorOptanteacpe_UsuarioCreacionNavigation = new HashSet<tbActividadesPorOptante>();
            tbActividadesPorOptanteacpe_UsuarioModificacionNavigation = new HashSet<tbActividadesPorOptante>();
            tbActividadesacti_UsuarioCreacionNavigation = new HashSet<tbActividades>();
            tbActividadesacti_UsuarioModificacionNavigation = new HashSet<tbActividades>();
            tbBancosbanc_UsuarioCreacionNavigation = new HashSet<tbBancos>();
            tbBancosbanc_UsuarioModificacionNavigation = new HashSet<tbBancos>();
            tbBeneficiosbene_UsuarioCreacionNavigation = new HashSet<tbBeneficios>();
            tbBeneficiosbene_UsuarioModificacionNavigation = new HashSet<tbBeneficios>();
            tbCarrerascarr_UsuarioCreacionNavigation = new HashSet<tbCarreras>();
            tbCarrerascarr_UsuarioModificacionNavigation = new HashSet<tbCarreras>();
            tbComponentescomp_UsuarioCreacionNavigation = new HashSet<tbComponentes>();
            tbComponentescomp_UsuarioModificacionNavigation = new HashSet<tbComponentes>();
            tbCuestionarioscues_UsuarioCreacionNavigation = new HashSet<tbCuestionarios>();
            tbCuestionarioscues_UsuarioModificacionNavigation = new HashSet<tbCuestionarios>();
            tbDepartamentosdepa_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbDiscusionesdisc_UsuarioCreacionNavigation = new HashSet<tbDiscusiones>();
            tbDiscusionesdisc_UsuarioModificacionNavigation = new HashSet<tbDiscusiones>();
            tbDocumentosOptantesdoop_UsuarioCreacionNavigation = new HashSet<tbDocumentosOptantes>();
            tbDocumentosOptantesdoop_UsuarioModificacionNavigation = new HashSet<tbDocumentosOptantes>();
            tbDocumentosdocu_UsuarioCreacionNavigation = new HashSet<tbDocumentos>();
            tbDocumentosdocu_UsuarioModificacionNavigation = new HashSet<tbDocumentos>();
            tbEmpleadosempl_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEmpresasempr_UsuarioCreacionNavigation = new HashSet<tbEmpresas>();
            tbEmpresasempr_UsuarioModificacionNavigation = new HashSet<tbEmpresas>();
            tbEstadosCivilescivi_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilescivi_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacultadesfacu_UsuarioCreacionNavigation = new HashSet<tbFacultades>();
            tbFacultadesfacu_UsuarioModificacionNavigation = new HashSet<tbFacultades>();
            tbForosPorActividadfoac_UsuarioCreacionNavigation = new HashSet<tbForosPorActividad>();
            tbForosPorActividadfoac_UsuarioModificacionNavigation = new HashSet<tbForosPorActividad>();
            tbForosPorEmpleadosfoem_UsuarioCreacionNavigation = new HashSet<tbForosPorEmpleados>();
            tbForosPorEmpleadosfoem_UsuarioModificacionNavigation = new HashSet<tbForosPorEmpleados>();
            tbForosforo_UsuarioCreacionNavigation = new HashSet<tbForos>();
            tbForosforo_UsuarioModificacionNavigation = new HashSet<tbForos>();
            tbHojaTiempoPorOptantehoto_UsuarioCreacionNavigation = new HashSet<tbHojaTiempoPorOptante>();
            tbHojaTiempoPorOptantehoto_UsuarioModificacionNavigation = new HashSet<tbHojaTiempoPorOptante>();
            tbHojaTiempohoti_UsuarioCreacionNavigation = new HashSet<tbHojaTiempo>();
            tbHojaTiempohoti_UsuarioModificacionNavigation = new HashSet<tbHojaTiempo>();
            tbModulosmodu_UsuarioCreacionNavigation = new HashSet<tbModulos>();
            tbModulosmodu_UsuarioModificacionNavigation = new HashSet<tbModulos>();
            tbMunicipiosmuni_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbNotificacionesPorUsuarionapu_UsuarioCreacionNavigation = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesPorUsuarionapu_UsuarioModificacionNavigation = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesPorUsuariousua = new HashSet<tbNotificacionesPorUsuario>();
            tbNotificacionesnoti_UsuarioCreacionNavigation = new HashSet<tbNotificaciones>();
            tbNotificacionesnoti_UsuarioModificacionNavigation = new HashSet<tbNotificaciones>();
            tbOptantesopta_UsuarioCreacionNavigation = new HashSet<tbOptantes>();
            tbOptantesopta_UsuarioModificacionNavigation = new HashSet<tbOptantes>();
            tbPreguntasFrecuentesprfr_UsuarioCreacionNavigation = new HashSet<tbPreguntasFrecuentes>();
            tbPreguntasFrecuentesprfr_UsuarioModificacionNavigation = new HashSet<tbPreguntasFrecuentes>();
            tbProyectospryt_UsuarioCreacionNavigation = new HashSet<tbProyectos>();
            tbProyectospryt_UsuarioModificacionNavigation = new HashSet<tbProyectos>();
            tbPuestospust_UsuarioCreacionNavigation = new HashSet<tbPuestos>();
            tbPuestospust_UsuarioModificacionNavigation = new HashSet<tbPuestos>();
            tbRecibosreci_UsuarioCreacionNavigation = new HashSet<tbRecibos>();
            tbRecibosreci_UsuarioModificacionNavigation = new HashSet<tbRecibos>();
            tbRegionalCorporativareco_UsuarioCreacionNavigation = new HashSet<tbRegionalCorporativa>();
            tbRegionalCorporativareco_UsuarioModificacionNavigation = new HashSet<tbRegionalCorporativa>();
            tbRegionalesregi_UsuarioCreacionNavigation = new HashSet<tbRegionales>();
            tbRegionalesregi_UsuarioModificacionNavigation = new HashSet<tbRegionales>();
            tbRolesrole_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbTipoDocumentotido_UsuarioCreacionNavigation = new HashSet<tbTipoDocumento>();
            tbTipoDocumentotido_UsuarioModificacionNavigation = new HashSet<tbTipoDocumento>();
            tbTipoSangretisa_UsuarioCreacionNavigation = new HashSet<tbTipoSangre>();
            tbTipoSangretisa_UsuarioModificacionNavigation = new HashSet<tbTipoSangre>();
            tbTokens = new HashSet<tbTokens>();
            tbUniversidadesuniv_UsuarioCreacionNavigation = new HashSet<tbUniversidades>();
            tbUniversidadesuniv_UsuarioModificacionNavigation = new HashSet<tbUniversidades>();
        }

        [Key]
        public int usua_Id { get; set; }
        public int emop_Id { get; set; }
        public int? role_Id { get; set; }
        public bool usua_Administrador { get; set; }
        public bool usua_EsOptante { get; set; }
        [Required]
        [StringLength(60)]
        public string usua_Usuario { get; set; }
        [Required]
        public string usua_Clave { get; set; }
        public int? usua_CodigoReestablecer { get; set; }
        public int? usua_UsuarioCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        [ForeignKey(nameof(usua_UsuarioCreacion))]
        [InverseProperty(nameof(tbUsuarios.Inverseusua_UsuarioCreacionNavigation))]
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        [ForeignKey(nameof(usua_UsuarioModificacion))]
        [InverseProperty(nameof(tbUsuarios.Inverseusua_UsuarioModificacionNavigation))]
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbUsuarios.usua_UsuarioCreacionNavigation))]
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbUsuarios.usua_UsuarioModificacionNavigation))]
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbActividadesPorOptante.acpe_UsuarioCreacionNavigation))]
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptanteacpe_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbActividadesPorOptante.acpe_UsuarioModificacionNavigation))]
        public virtual ICollection<tbActividadesPorOptante> tbActividadesPorOptanteacpe_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbActividades.acti_UsuarioCreacionNavigation))]
        public virtual ICollection<tbActividades> tbActividadesacti_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbActividades.acti_UsuarioModificacionNavigation))]
        public virtual ICollection<tbActividades> tbActividadesacti_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbBancos.banc_UsuarioCreacionNavigation))]
        public virtual ICollection<tbBancos> tbBancosbanc_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbBancos.banc_UsuarioModificacionNavigation))]
        public virtual ICollection<tbBancos> tbBancosbanc_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbBeneficios.bene_UsuarioCreacionNavigation))]
        public virtual ICollection<tbBeneficios> tbBeneficiosbene_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbBeneficios.bene_UsuarioModificacionNavigation))]
        public virtual ICollection<tbBeneficios> tbBeneficiosbene_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbCarreras.carr_UsuarioCreacionNavigation))]
        public virtual ICollection<tbCarreras> tbCarrerascarr_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbCarreras.carr_UsuarioModificacionNavigation))]
        public virtual ICollection<tbCarreras> tbCarrerascarr_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbComponentes.comp_UsuarioCreacionNavigation))]
        public virtual ICollection<tbComponentes> tbComponentescomp_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbComponentes.comp_UsuarioModificacionNavigation))]
        public virtual ICollection<tbComponentes> tbComponentescomp_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbCuestionarios.cues_UsuarioCreacionNavigation))]
        public virtual ICollection<tbCuestionarios> tbCuestionarioscues_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbCuestionarios.cues_UsuarioModificacionNavigation))]
        public virtual ICollection<tbCuestionarios> tbCuestionarioscues_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbDepartamentos.depa_UsuarioCreacionNavigation))]
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbDepartamentos.depa_UsuarioModificacionNavigation))]
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbDiscusiones.disc_UsuarioCreacionNavigation))]
        public virtual ICollection<tbDiscusiones> tbDiscusionesdisc_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbDiscusiones.disc_UsuarioModificacionNavigation))]
        public virtual ICollection<tbDiscusiones> tbDiscusionesdisc_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbDocumentosOptantes.doop_UsuarioCreacionNavigation))]
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantesdoop_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbDocumentosOptantes.doop_UsuarioModificacionNavigation))]
        public virtual ICollection<tbDocumentosOptantes> tbDocumentosOptantesdoop_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbDocumentos.docu_UsuarioCreacionNavigation))]
        public virtual ICollection<tbDocumentos> tbDocumentosdocu_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbDocumentos.docu_UsuarioModificacionNavigation))]
        public virtual ICollection<tbDocumentos> tbDocumentosdocu_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbEmpleados.empl_UsuarioCreacionNavigation))]
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbEmpleados.empl_UsuarioModificacionNavigation))]
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbEmpresas.empr_UsuarioCreacionNavigation))]
        public virtual ICollection<tbEmpresas> tbEmpresasempr_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbEmpresas.empr_UsuarioModificacionNavigation))]
        public virtual ICollection<tbEmpresas> tbEmpresasempr_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbEstadosCiviles.civi_UsuarioCreacionNavigation))]
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilescivi_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbEstadosCiviles.civi_UsuarioModificacionNavigation))]
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilescivi_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbFacultades.facu_UsuarioCreacionNavigation))]
        public virtual ICollection<tbFacultades> tbFacultadesfacu_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbFacultades.facu_UsuarioModificacionNavigation))]
        public virtual ICollection<tbFacultades> tbFacultadesfacu_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbForosPorActividad.foac_UsuarioCreacionNavigation))]
        public virtual ICollection<tbForosPorActividad> tbForosPorActividadfoac_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbForosPorActividad.foac_UsuarioModificacionNavigation))]
        public virtual ICollection<tbForosPorActividad> tbForosPorActividadfoac_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbForosPorEmpleados.foem_UsuarioCreacionNavigation))]
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleadosfoem_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbForosPorEmpleados.foem_UsuarioModificacionNavigation))]
        public virtual ICollection<tbForosPorEmpleados> tbForosPorEmpleadosfoem_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbForos.foro_UsuarioCreacionNavigation))]
        public virtual ICollection<tbForos> tbForosforo_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbForos.foro_UsuarioModificacionNavigation))]
        public virtual ICollection<tbForos> tbForosforo_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbHojaTiempoPorOptante.hoto_UsuarioCreacionNavigation))]
        public virtual ICollection<tbHojaTiempoPorOptante> tbHojaTiempoPorOptantehoto_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbHojaTiempoPorOptante.hoto_UsuarioModificacionNavigation))]
        public virtual ICollection<tbHojaTiempoPorOptante> tbHojaTiempoPorOptantehoto_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbHojaTiempo.hoti_UsuarioCreacionNavigation))]
        public virtual ICollection<tbHojaTiempo> tbHojaTiempohoti_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbHojaTiempo.hoti_UsuarioModificacionNavigation))]
        public virtual ICollection<tbHojaTiempo> tbHojaTiempohoti_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbModulos.modu_UsuarioCreacionNavigation))]
        public virtual ICollection<tbModulos> tbModulosmodu_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbModulos.modu_UsuarioModificacionNavigation))]
        public virtual ICollection<tbModulos> tbModulosmodu_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbMunicipios.muni_UsuarioCreacionNavigation))]
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbMunicipios.muni_UsuarioModificacionNavigation))]
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbNotificacionesPorUsuario.napu_UsuarioCreacionNavigation))]
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuarionapu_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbNotificacionesPorUsuario.napu_UsuarioModificacionNavigation))]
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuarionapu_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbNotificacionesPorUsuario.usua))]
        public virtual ICollection<tbNotificacionesPorUsuario> tbNotificacionesPorUsuariousua { get; set; }
        [InverseProperty(nameof(tbNotificaciones.noti_UsuarioCreacionNavigation))]
        public virtual ICollection<tbNotificaciones> tbNotificacionesnoti_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbNotificaciones.noti_UsuarioModificacionNavigation))]
        public virtual ICollection<tbNotificaciones> tbNotificacionesnoti_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbOptantes.opta_UsuarioCreacionNavigation))]
        public virtual ICollection<tbOptantes> tbOptantesopta_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbOptantes.opta_UsuarioModificacionNavigation))]
        public virtual ICollection<tbOptantes> tbOptantesopta_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbPreguntasFrecuentes.prfr_UsuarioCreacionNavigation))]
        public virtual ICollection<tbPreguntasFrecuentes> tbPreguntasFrecuentesprfr_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbPreguntasFrecuentes.prfr_UsuarioModificacionNavigation))]
        public virtual ICollection<tbPreguntasFrecuentes> tbPreguntasFrecuentesprfr_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbProyectos.pryt_UsuarioCreacionNavigation))]
        public virtual ICollection<tbProyectos> tbProyectospryt_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbProyectos.pryt_UsuarioModificacionNavigation))]
        public virtual ICollection<tbProyectos> tbProyectospryt_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbPuestos.pust_UsuarioCreacionNavigation))]
        public virtual ICollection<tbPuestos> tbPuestospust_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbPuestos.pust_UsuarioModificacionNavigation))]
        public virtual ICollection<tbPuestos> tbPuestospust_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbRecibos.reci_UsuarioCreacionNavigation))]
        public virtual ICollection<tbRecibos> tbRecibosreci_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbRecibos.reci_UsuarioModificacionNavigation))]
        public virtual ICollection<tbRecibos> tbRecibosreci_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbRegionalCorporativa.reco_UsuarioCreacionNavigation))]
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativareco_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbRegionalCorporativa.reco_UsuarioModificacionNavigation))]
        public virtual ICollection<tbRegionalCorporativa> tbRegionalCorporativareco_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbRegionales.regi_UsuarioCreacionNavigation))]
        public virtual ICollection<tbRegionales> tbRegionalesregi_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbRegionales.regi_UsuarioModificacionNavigation))]
        public virtual ICollection<tbRegionales> tbRegionalesregi_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbRoles.role_UsuarioCreacionNavigation))]
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbRoles.role_UsuarioModificacionNavigation))]
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbTipoDocumento.tido_UsuarioCreacionNavigation))]
        public virtual ICollection<tbTipoDocumento> tbTipoDocumentotido_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbTipoDocumento.tido_UsuarioModificacionNavigation))]
        public virtual ICollection<tbTipoDocumento> tbTipoDocumentotido_UsuarioModificacionNavigation { get; set; }
        [InverseProperty(nameof(tbTipoSangre.tisa_UsuarioCreacionNavigation))]
        public virtual ICollection<tbTipoSangre> tbTipoSangretisa_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbTipoSangre.tisa_UsuarioModificacionNavigation))]
        public virtual ICollection<tbTipoSangre> tbTipoSangretisa_UsuarioModificacionNavigation { get; set; }
        [InverseProperty("usua")]
        public virtual ICollection<tbTokens> tbTokens { get; set; }
        [InverseProperty(nameof(tbUniversidades.univ_UsuarioCreacionNavigation))]
        public virtual ICollection<tbUniversidades> tbUniversidadesuniv_UsuarioCreacionNavigation { get; set; }
        [InverseProperty(nameof(tbUniversidades.univ_UsuarioModificacionNavigation))]
        public virtual ICollection<tbUniversidades> tbUniversidadesuniv_UsuarioModificacionNavigation { get; set; }
    }
}